Feature: Did you know embedded standard scrollbar

  Scenario: Embedded Browse all list shows a visible overlay scrollbar
    Given the extension is in a clean state
    When I move the Dev Host to 0, 0
    And I resize the Dev Host to 1000 by 760
    And I execute command "workbench.action.closeSidebar"
    And I execute command "workbench.action.closeAuxiliaryBar"
    And I execute command "workbench.action.closePanel"
    And I wait 2 seconds
    When I execute command "kustoWorkbench.dev.resetDidYouKnowState"
    And I open file "tests/vscode-extension-tester/e2e/default/did-you-know-embedded-popup/fixtures/embedded-did-you-know.kqlx" in the editor
    And I wait for "kw-query-section .monaco-editor" in the webview for 25 seconds
    And I execute command "kustoWorkbench.test.openEmbeddedDidYouKnow"
    And I wait for "#kw-embedded-tutorial-viewer-host kw-tutorial-viewer" in the webview for 25 seconds
    And I evaluate "(async () => { const sleep = ms => new Promise(resolve => setTimeout(resolve, ms)); const waitFor = async predicate => { for (let attempt = 0; attempt < 160; attempt++) { const value = await predicate(); if (value) return value; await sleep(100); } throw new Error('Timed out waiting for embedded Browse all scrollbar'); }; const host = await waitFor(() => document.querySelector('#kw-embedded-tutorial-viewer-host')); const viewer = await waitFor(() => host.querySelector('kw-tutorial-viewer')); const root = viewer.shadowRoot; await waitFor(async () => { await viewer.updateComplete; return root.querySelector('[data-testid=tutorial-mode-standard]'); }); root.querySelector('[data-testid=tutorial-mode-standard]').click(); await waitFor(async () => { await viewer.updateComplete; return root.querySelector('[data-testid=tutorial-viewer-mode-standard]') && root.querySelector('[data-testid=tutorial-list]'); }); const list = root.querySelector('[data-testid=tutorial-list]'); await waitFor(() => list.scrollHeight > list.clientHeight); const scrollbar = await waitFor(() => { const listRect = list.getBoundingClientRect(); for (const candidate of root.querySelectorAll('.os-scrollbar-vertical')) { const rect = candidate.getBoundingClientRect(); const style = getComputedStyle(candidate); const handle = candidate.querySelector('.os-scrollbar-handle'); const handleRect = handle?.getBoundingClientRect(); const handleStyle = handle ? getComputedStyle(handle) : null; const besideList = Math.abs(rect.right - listRect.right) <= 20 && rect.bottom > listRect.top && rect.top < listRect.bottom; const visibleColor = !!handleStyle && handleStyle.backgroundColor !== 'rgba(0, 0, 0, 0)' && handleStyle.backgroundColor !== 'transparent'; const usable = !candidate.classList.contains('os-scrollbar-unusable') && !!handleStyle && Number(handleStyle.opacity) > 0; if (besideList && usable && handle && handleRect && rect.width >= 10 && rect.height > 20 && handleRect.width >= 6 && handleRect.height > 8 && style.visibility === 'visible' && Number(style.opacity) > 0 && visibleColor) return candidate; } return null; }); const listRect = list.getBoundingClientRect(); const rect = scrollbar.getBoundingClientRect(); const handle = scrollbar.querySelector('.os-scrollbar-handle'); const handleRect = handle.getBoundingClientRect(); const handleStyle = getComputedStyle(handle); viewer.setAttribute('data-embedded-scrollbar', 'PASS'); return { list: { rect: listRect.toJSON(), scrollHeight: list.scrollHeight, clientHeight: list.clientHeight, dataOverlayscrollbars: list.getAttribute('data-overlayscrollbars') }, scrollbar: rect.toJSON(), handle: handleRect.toJSON(), handleColor: handleStyle.backgroundColor, handleOpacity: handleStyle.opacity, scrollbarClass: scrollbar.className }; })()" in the webview for 25 seconds
    Then element "#kw-embedded-tutorial-viewer-host kw-tutorial-viewer[data-embedded-scrollbar='PASS']" should exist
    Then I take a screenshot "01-embedded-standard-scrollbar"
