Feature: Kusto connection dialog entry points

  Background:
    Given the extension is in a clean state
    And I capture the output channel "Kusto Workbench"
    And I wait 2 seconds

  Scenario: Kusto add connection dialog is consistent across entry points
    When I execute command "kusto.openQueryEditor"
    And I wait 3 seconds
    When I wait for "#queries-container" in the webview for 20 seconds

    When I evaluate "(() => { window.__kustoConnectionDialogSmoke = {}; const signatureFor = form => { const root = form?.shadowRoot; if (!root) throw new Error('form has no shadow root'); return { labels: [...root.querySelectorAll('label')].map(label => (label.textContent || '').trim()), placeholders: [...root.querySelectorAll('input')].map(input => input.getAttribute('placeholder') || ''), buttons: [...root.querySelectorAll('button')].map(button => (button.textContent || '').trim()) }; }; const setValue = (root, testId, value) => { const input = root.querySelector(`[data-testid=${testId}]`); if (!input) throw new Error('missing input ' + testId); input.value = value; input.dispatchEvent(new Event('input', { bubbles: true, composed: true })); }; const section = document.querySelector('kw-query-section'); if (!section) throw new Error('kw-query-section missing'); const dropdown = section.shadowRoot?.querySelector('kw-dropdown[data-testid=cluster-dropdown]'); if (!dropdown) throw new Error('cluster dropdown missing'); dropdown.shadowRoot?.querySelector('.kusto-dropdown-btn')?.click(); const action = [...dropdown.shadowRoot.querySelectorAll('.kusto-dropdown-action')].find(node => (node.textContent || '').includes('Enter new cluster')); if (!action) throw new Error('Enter new cluster action missing'); action.click(); const form = section.shadowRoot?.querySelector('kw-kusto-connection-form'); if (!form) throw new Error('query add form did not open'); const root = form.shadowRoot; const signature = signatureFor(form); if (!signature.buttons.includes('Test Connection')) throw new Error('query dialog missing Test Connection: ' + JSON.stringify(signature)); setValue(root, 'kusto-conn-name', 'Query Draft'); setValue(root, 'kusto-conn-cluster-url', 'query-draft.kusto.windows.net'); setValue(root, 'kusto-conn-database', 'Samples'); const messages = []; window.__e2eCaptureHostMessage = message => { messages.push(message); return false; }; try { root.querySelector('[data-testid=kusto-conn-test]')?.click(); } finally { delete window.__e2eCaptureHostMessage; } const testMessage = messages.find(message => message?.type === 'testKustoConnection'); if (!testMessage) throw new Error('query dialog did not post testKustoConnection'); if (testMessage.clusterUrl !== 'query-draft.kusto.windows.net' || testMessage.database !== 'Samples') throw new Error('unexpected query test payload: ' + JSON.stringify(testMessage)); window.__kustoConnectionDialogSmoke.querySignature = signature; section.setAddConnectionTestResult(''); section.shadowRoot?.querySelector('.add-connection-close')?.click(); return 'query dialog signature ' + JSON.stringify(signature); })()" in the webview

    When I execute command "kusto.manageConnections"
    And I wait 2 seconds
    When I wait for "kw-connection-manager" in the webview for 20 seconds
    When I evaluate "(() => { const signatureFor = form => { const root = form?.shadowRoot; if (!root) throw new Error('form has no shadow root'); return { labels: [...root.querySelectorAll('label')].map(label => (label.textContent || '').trim()), placeholders: [...root.querySelectorAll('input')].map(input => input.getAttribute('placeholder') || ''), buttons: [...root.querySelectorAll('button')].map(button => (button.textContent || '').trim()) }; }; const setValue = (root, testId, value) => { const input = root.querySelector(`[data-testid=${testId}]`); if (!input) throw new Error('missing input ' + testId); input.value = value; input.dispatchEvent(new Event('input', { bubbles: true, composed: true })); }; const cm = document.querySelector('kw-connection-manager'); if (!cm) throw new Error('connection manager missing'); const root = cm.shadowRoot; const add = root?.querySelector('[data-testid=cm-add-connection]'); if (!add) throw new Error('connection manager add button missing'); add.click(); const form = root?.querySelector('kw-kusto-connection-form'); if (!form) throw new Error('connection manager add form did not open'); const signature = signatureFor(form); if (!signature.buttons.includes('Test Connection')) throw new Error('connection manager dialog missing Test Connection: ' + JSON.stringify(signature)); const expected = window.__kustoConnectionDialogSmoke?.querySignature; if (JSON.stringify(signature) !== JSON.stringify(expected)) throw new Error('connection manager dialog differs from query dialog. query=' + JSON.stringify(expected) + ' manager=' + JSON.stringify(signature)); const formRoot = form.shadowRoot; setValue(formRoot, 'kusto-conn-name', 'Manager Draft'); setValue(formRoot, 'kusto-conn-cluster-url', 'manager-draft.kusto.windows.net'); setValue(formRoot, 'kusto-conn-database', 'Samples'); const messages = []; const original = cm._vscode.postMessage.bind(cm._vscode); cm._vscode.postMessage = message => { messages.push(message); }; try { formRoot.querySelector('[data-testid=kusto-conn-test]')?.click(); } finally { cm._vscode.postMessage = original; } const testMessage = messages.find(message => message?.type === 'connection.test'); if (!testMessage) throw new Error('connection manager dialog did not post connection.test'); if (testMessage.clusterUrl !== 'manager-draft.kusto.windows.net' || testMessage.database !== 'Samples') throw new Error('unexpected connection manager test payload: ' + JSON.stringify(testMessage)); return 'connection manager dialog matches query dialog and posts draft test'; })()" in the webview
