Feature: Tutorial viewer

  Background:
    Given the extension is in a clean state
    When I move the Dev Host to 0, 0
    And I resize the Dev Host to 1200 by 900
    And I execute command "workbench.action.closeSidebar"
    And I execute command "workbench.action.closeAuxiliaryBar"
    And I execute command "workbench.action.closePanel"
    And I capture the output channel "Kusto Workbench"
    And I wait 2 seconds

  Scenario: Open searchable tutorials and toggle subscription controls
    When I execute command "kusto.openTutorials"
    And I wait 3 seconds
    When I wait for "kw-tutorial-viewer" in the webview for 25 seconds
    And I evaluate "(() => { const viewer = document.querySelector('kw-tutorial-viewer'); const root = viewer.shadowRoot; if (!root.querySelector('[data-testid=tutorial-viewer-title]')) throw new Error('missing title'); if (!root.querySelector('[data-testid=tutorial-viewer-mode-standard]')) throw new Error('standard mode did not render'); const search = root.querySelector('kw-search-bar'); if (!search) throw new Error('missing search'); return 'tutorial viewer rendered'; })()" in the webview
    And I evaluate "(() => { const viewer = document.querySelector('kw-tutorial-viewer'); const root = viewer.shadowRoot; const search = root.querySelector('kw-search-bar'); search.dispatchEvent(new CustomEvent('search-input', { detail: { query: 'chart' }, bubbles: true, composed: true })); if (!root.textContent.toLowerCase().includes('chart')) throw new Error('search did not keep chart tutorial visible'); return 'search verified'; })()" in the webview
    And I evaluate "(() => { const viewer = document.querySelector('kw-tutorial-viewer'); const root = viewer.shadowRoot; const row = () => root.querySelector('[data-testid=tutorial-category-row][data-category-id=charts]'); const bellButton = () => row()?.querySelector('[data-testid=tutorial-category-subscribe]'); const waitFor = async (predicate, label) => { for (let attempt = 0; attempt < 30; attempt++) { await viewer.updateComplete; const value = predicate(); if (value) return value; await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('timed out waiting for ' + label); }; return (async () => { if (!row()) throw new Error('missing Charts category row'); const bell = bellButton(); if (!bell) throw new Error('missing category bell toggle'); if (!bell.getAttribute('aria-label').includes('Charts')) throw new Error('bell label does not name category'); bell.click(); const popup = await waitFor(() => row()?.querySelector('[data-testid=tutorial-category-channel]'), 'pop-up channel pill'); if (!popup.textContent.includes('pop-up')) throw new Error('channel did not default to pop-up'); if (!popup.title.includes('automatically fire up the tutorial UI')) throw new Error('missing pop-up explanation'); popup.click(); let notification = await waitFor(() => { const pill = row()?.querySelector('[data-testid=tutorial-category-channel]'); return pill?.textContent.includes('notification') ? pill : null; }, 'notification channel pill'); if (!notification.title.includes('VS Code style notification')) throw new Error('missing notification explanation'); bellButton().click(); await waitFor(() => !row()?.querySelector('[data-testid=tutorial-category-channel]') && bellButton()?.getAttribute('aria-pressed') === 'false', 'unsubscribed category'); bellButton().click(); const popupAgain = await waitFor(() => row()?.querySelector('[data-testid=tutorial-category-channel]'), 'resubscribed pop-up channel pill'); popupAgain.click(); notification = await waitFor(() => { const pill = row()?.querySelector('[data-testid=tutorial-category-channel]'); return pill?.textContent.includes('notification') ? pill : null; }, 'resubscribed notification channel pill'); row().querySelector('.category-main').click(); await waitFor(() => row().classList.contains('active') && root.querySelector('.detail h2')?.textContent.includes('Build a chart'), 'Charts detail content'); return 'subscription controls verified'; })(); })()" in the webview
    Then I take a screenshot "01-tutorial-viewer-standard"
    And I evaluate "(() => { const viewer = document.querySelector('kw-tutorial-viewer'); const root = viewer.shadowRoot; return (async () => { const search = root.querySelector('kw-search-bar'); search.dispatchEvent(new CustomEvent('search-input', { detail: { query: '' }, bubbles: true, composed: true })); await viewer.updateComplete; const agent = root.querySelector('[data-testid=tutorial-category-row][data-category-id=agent] .category-main'); if (!agent) throw new Error('missing Agent category row'); agent.click(); await viewer.updateComplete; const items = Array.from(root.querySelectorAll('[data-testid=tutorial-item]')); if (items.length < 2) throw new Error('need at least two tutorials for keyboard navigation'); const first = items[0]; const secondId = items[1].dataset.tutorialId; first.focus(); first.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, composed: true })); await viewer.updateComplete; await new Promise(resolve => queueMicrotask(resolve)); const active = root.activeElement; if (!active?.matches?.('[data-testid=tutorial-item]')) throw new Error('keyboard navigation did not keep focus on tutorials'); if (active.dataset.tutorialId !== secondId) throw new Error('keyboard navigation did not move to the next tutorial'); return 'keyboard navigation verified'; })(); })()" in the webview
    And I evaluate "(() => { const viewer = document.querySelector('kw-tutorial-viewer'); const root = viewer.shadowRoot; const agent = root.querySelector('[data-testid=tutorial-category-row][data-category-id=agent] .category-main'); if (!agent) throw new Error('missing Agent category row'); agent.click(); return viewer.updateComplete.then(() => { const first = root.querySelector('[data-testid=tutorial-item]'); if (!first) throw new Error('missing first filtered tutorial'); first.click(); return viewer.updateComplete.then(() => { root.querySelector('[data-testid=tutorial-mode-focused]').click(); return viewer.updateComplete.then(() => { if (!root.querySelector('[data-testid=tutorial-viewer-mode-focused]')) throw new Error('focused mode did not render'); const next = root.querySelector('[data-testid=tutorial-next]'); if (!next || next.disabled) throw new Error('focused next navigation unavailable'); next.click(); return viewer.updateComplete.then(() => { if (!root.textContent.includes('Refine')) throw new Error('focused next navigation did not advance within category'); const standard = root.querySelector('[data-testid=tutorial-mode-standard]'); if (!standard) throw new Error('missing standard mode button'); return 'focused mode verified'; }); }); }); }); })()" in the webview
    Then I take a screenshot "02-tutorial-viewer-focused"
