import { TUTORIAL_CATALOG_SCHEMA_VERSION, type TutorialCatalog } from '../../shared/tutorials/tutorialCatalog';

export const BUILT_IN_TUTORIAL_CATALOG: TutorialCatalog = {
	schemaVersion: TUTORIAL_CATALOG_SCHEMA_VERSION,
	generatedAt: '2026-05-01T00:00:00.000Z',
	categories: [
		{ id: 'agent', title: 'Agent workflow', description: 'Use the Kusto Workbench agent to create and refine notebooks.', sortOrder: 10 },
		{ id: 'editor', title: 'Editor workflow', description: 'Write queries, run them, and keep work in Kusto notebook files.', sortOrder: 20 },
		{ id: 'results', title: 'Results and tables', description: 'Explore, filter, and transform query results.', sortOrder: 30 },
		{ id: 'charts', title: 'Charts', description: 'Build visualizations from query results.', sortOrder: 40 },
		{ id: 'copilot', title: 'Copilot', description: 'Use Copilot chat and the custom agent effectively.', sortOrder: 50 },
	],
	tutorials: [
		{
			id: 'agent-add-connection',
			title: 'Add a Kusto connection',
			summary: 'Connect to a Kusto cluster and database before asking the agent to build reports.',
			categoryId: 'agent',
			contentUrl: 'media/walkthroughs/agent-01-add-connection.md',
			minExtensionVersion: '0.0.0',
			updateToken: 'builtin-agent-add-connection-2026-05-01',
			tags: ['connection', 'cluster', 'database', 'agent'],
			sortOrder: 10,
			nativeWalkthroughId: 'kusto-workbench.agent-first',
			actions: [{ id: 'manage-connections', title: 'Manage Connections', command: 'kusto.manageConnections' }],
		},
		{
			id: 'agent-first-chart',
			title: 'Ask the agent for your first chart',
			summary: 'Use the agent to create a query and chart from a natural-language request.',
			categoryId: 'agent',
			contentUrl: 'media/walkthroughs/agent-02-first-chart.md',
			minExtensionVersion: '0.0.0',
			updateToken: 'builtin-agent-first-chart-2026-05-01',
			tags: ['agent', 'chart', 'copilot'],
			sortOrder: 20,
			nativeWalkthroughId: 'kusto-workbench.agent-first',
			actions: [{ id: 'open-agent', title: 'Open Kusto Workbench Agent', command: 'kusto.openCustomAgent' }],
		},
		{
			id: 'agent-refine-query',
			title: 'Refine with follow-up requests',
			summary: 'Ask the agent to iterate on existing sections while keeping file context.',
			categoryId: 'agent',
			contentUrl: 'media/walkthroughs/agent-03-refine-query.md',
			minExtensionVersion: '0.0.0',
			updateToken: 'builtin-agent-refine-query-2026-05-01',
			tags: ['agent', 'follow-up', 'query'],
			sortOrder: 30,
			nativeWalkthroughId: 'kusto-workbench.agent-first',
		},
		{
			id: 'agent-explore-report',
			title: 'Explore and tweak your report',
			summary: 'Inspect generated sections, adjust query text, and tune chart settings.',
			categoryId: 'agent',
			contentUrl: 'media/walkthroughs/agent-04-explore-report.md',
			minExtensionVersion: '0.0.0',
			updateToken: 'builtin-agent-explore-report-2026-05-01',
			tags: ['agent', 'report', 'chart', 'results'],
			sortOrder: 40,
			nativeWalkthroughId: 'kusto-workbench.agent-first',
		},
		{
			id: 'editor-add-connection',
			title: 'Add a Kusto connection',
			summary: 'Create a saved connection for editor-first work.',
			categoryId: 'editor',
			contentUrl: 'media/walkthroughs/editor-01-add-connection.md',
			minExtensionVersion: '0.0.0',
			updateToken: 'builtin-editor-add-connection-2026-05-01',
			tags: ['connection', 'cluster', 'database', 'editor'],
			sortOrder: 50,
			nativeWalkthroughId: 'kusto-workbench.editor-first',
			actions: [{ id: 'manage-connections', title: 'Manage Connections', command: 'kusto.manageConnections' }],
		},
		{
			id: 'editor-first-query',
			title: 'Run your first query',
			summary: 'Open the query editor and execute your first KQL query.',
			categoryId: 'editor',
			contentUrl: 'media/walkthroughs/editor-02-first-query.md',
			minExtensionVersion: '0.0.0',
			updateToken: 'builtin-editor-first-query-2026-05-01',
			tags: ['query', 'editor', 'kql'],
			sortOrder: 60,
			nativeWalkthroughId: 'kusto-workbench.editor-first',
			actions: [{ id: 'open-editor', title: 'Open Query Editor', command: 'kusto.openQueryEditor' }],
		},
		{
			id: 'editor-caching-run-modes',
			title: 'Caching and run modes',
			summary: 'Use Take, Sample, Run Query, and result caching while iterating.',
			categoryId: 'editor',
			contentUrl: 'media/walkthroughs/editor-03-caching-run-modes.md',
			minExtensionVersion: '0.0.0',
			updateToken: 'builtin-editor-caching-run-modes-2026-05-01',
			tags: ['cache', 'run mode', 'query'],
			sortOrder: 70,
			nativeWalkthroughId: 'kusto-workbench.editor-first',
		},
		{
			id: 'editor-table-tools',
			title: 'Table tools',
			summary: 'Sort, filter, inspect values, and add transformation sections.',
			categoryId: 'results',
			contentUrl: 'media/walkthroughs/editor-04-table-tools.md',
			minExtensionVersion: '0.0.0',
			updateToken: 'builtin-editor-table-tools-2026-05-01',
			tags: ['table', 'filter', 'sort', 'transformation'],
			sortOrder: 80,
			nativeWalkthroughId: 'kusto-workbench.editor-first',
		},
		{
			id: 'editor-build-chart',
			title: 'Build a chart',
			summary: 'Create and configure a chart section from query results.',
			categoryId: 'charts',
			contentUrl: 'media/walkthroughs/editor-05-build-chart.md',
			minExtensionVersion: '0.0.0',
			updateToken: 'builtin-editor-build-chart-2026-05-01',
			tags: ['chart', 'visualization', 'bar', 'line'],
			sortOrder: 90,
			nativeWalkthroughId: 'kusto-workbench.editor-first',
		},
		{
			id: 'editor-copilot-chat',
			title: 'Copilot Chat: AI-assisted editing',
			summary: 'Use the integrated Copilot button to write and refine individual queries.',
			categoryId: 'copilot',
			contentUrl: 'media/walkthroughs/editor-06-copilot-chat.md',
			minExtensionVersion: '0.0.0',
			updateToken: 'builtin-editor-copilot-chat-2026-05-01',
			tags: ['copilot', 'chat', 'query'],
			sortOrder: 100,
			nativeWalkthroughId: 'kusto-workbench.editor-first',
		},
		{
			id: 'editor-agent',
			title: 'The custom agent',
			summary: 'Use the custom agent for full-notebook orchestration across sections.',
			categoryId: 'copilot',
			contentUrl: 'media/walkthroughs/editor-07-agent.md',
			minExtensionVersion: '0.0.0',
			updateToken: 'builtin-editor-agent-2026-05-01',
			tags: ['agent', 'copilot', 'notebook'],
			sortOrder: 110,
			nativeWalkthroughId: 'kusto-workbench.editor-first',
			actions: [{ id: 'open-agent', title: 'Open Kusto Workbench Agent', command: 'kusto.openCustomAgent' }],
		},
	],
};

export const BUILT_IN_TUTORIAL_CONTENT_PATHS: Record<string, string> = Object.fromEntries(
	BUILT_IN_TUTORIAL_CATALOG.tutorials.map(tutorial => [tutorial.id, tutorial.contentUrl]),
);

export const REMOTE_TUTORIAL_FALLBACK_CONTENT_PATHS: Record<string, string> = {
	'agent-first-report': 'media/walkthroughs/agent-02-first-chart.md',
	'editor-first-query': 'media/walkthroughs/editor-02-first-query.md',
	'table-tools': 'media/walkthroughs/editor-04-table-tools.md',
	'build-chart': 'media/walkthroughs/editor-05-build-chart.md',
	'copilot-chat': 'media/walkthroughs/editor-06-copilot-chat.md',
};
