Feature: Did you know regressions

  Background:
    Given the extension is in a clean state
    When I move the Dev Host to 0, 0
    And I resize the Dev Host to 1200 by 900
    And I execute command "workbench.action.closeSidebar"
    And I execute command "workbench.action.closeAuxiliaryBar"
    And I execute command "workbench.action.closePanel"
    And I capture the output channel "Kusto Workbench"
    And I wait 2 seconds

  Scenario: Browse all controls already-seen content while compact starts from unseen content
    When I execute command "kusto.openTutorials"
    And I wait for "kw-tutorial-viewer" in the webview for 25 seconds
    And I evaluate "(async () => { const sleep = ms => new Promise(resolve => setTimeout(resolve, ms)); const waitFor = async predicate => { for (let attempt = 0; attempt < 160; attempt++) { const value = await predicate(); if (value) return value; await sleep(100); } throw new Error('Timed out waiting for Browse all seen-toggle regression state'); }; const viewer = await waitFor(() => document.querySelector('kw-tutorial-viewer')); const root = viewer.shadowRoot; await waitFor(async () => { await viewer.updateComplete; return viewer.snapshot && root.querySelectorAll('[data-testid=tutorial-item]').length > 2 && root.querySelector('[data-testid=tutorial-standard-next]'); }); const allIds = viewer.snapshot.catalog.content.map(tutorial => tutorial.id); const seenId = allIds[1]; root.querySelector('[data-testid=tutorial-standard-next]').click(); await waitFor(async () => { await viewer.updateComplete; const item = viewer.snapshot.catalog.content.find(tutorial => tutorial.id === seenId); return item && item.unseen === false; }); const showSeen = root.querySelector('[data-testid=tutorial-show-seen-toggle] input'); if (!showSeen || showSeen.checked !== true) throw new Error('Browse all should expose a checked Show already seen checkbox'); showSeen.checked = false; showSeen.dispatchEvent(new Event('change', { bubbles: true })); await viewer.updateComplete; if (root.querySelector('[data-tutorial-id=' + seenId + ']')) throw new Error('Already-seen item remained visible after hiding seen content: ' + seenId); showSeen.checked = true; showSeen.dispatchEvent(new Event('change', { bubbles: true })); await viewer.updateComplete; if (!root.querySelector('[data-tutorial-id=' + seenId + ']')) throw new Error('Already-seen item did not return after showing seen content: ' + seenId); root.querySelector('[data-testid=tutorial-mode-compact]').click(); await waitFor(async () => { await viewer.updateComplete; return root.querySelector('[data-testid=tutorial-viewer-mode-compact]'); }); const compactIds = viewer.compactSessionTutorialIds || []; if (compactIds.includes(seenId)) throw new Error('Compact mode included a tutorial already seen before compact opened: ' + seenId); if (root.querySelector('[data-testid=tutorial-show-seen-toggle]')) throw new Error('Compact mode exposed the Browse all seen checkbox'); return { totalContent: allIds.length, seenId, compactCount: compactIds.length }; })()" in the webview for 25 seconds
    Then I take a screenshot "02-compact-unseen-only"

  Scenario: Category mute, cadence, and delivery preferences stay scoped to one category
    When I execute command "kusto.openTutorials"
    And I wait for "kw-tutorial-viewer" in the webview for 25 seconds
    And I evaluate "(async () => { const sleep = ms => new Promise(resolve => setTimeout(resolve, ms)); const waitFor = async predicate => { for (let attempt = 0; attempt < 100; attempt++) { const value = await predicate(); if (value) return value; await sleep(100); } throw new Error('Timed out priming charts preferences'); }; const viewer = await waitFor(() => document.querySelector('kw-tutorial-viewer')); const root = viewer.shadowRoot; await waitFor(async () => { await viewer.updateComplete; return viewer.snapshot && root.querySelectorAll('[data-testid=tutorial-item]').length > 5; }); const categoryIds = viewer.snapshot.catalog.categories.map(category => category.id); if (!categoryIds.includes('agent') || !categoryIds.includes('charts')) throw new Error('Expected agent and charts categories in local tutorial catalog'); const chartTutorialId = viewer.snapshot.catalog.content.find(tutorial => tutorial.categoryId === 'charts')?.id; const chartButton = await waitFor(() => root.querySelector('[data-tutorial-id=' + chartTutorialId + ']')); chartButton.click(); await waitFor(async () => { await viewer.updateComplete; return viewer.selectedTutorialId === chartTutorialId; }); const openMenuItem = async selector => { const existing = root.querySelector(selector); if (existing) return existing; const button = await waitFor(() => root.querySelector('[data-testid=tutorial-standard-mute]')); button.click(); await viewer.updateComplete; return waitFor(() => root.querySelector(selector)); }; const weekly = await openMenuItem('[data-testid=tutorial-compact-cadence-weekly]'); weekly.click(); await waitFor(async () => { await viewer.updateComplete; const charts = viewer.snapshot.preferences.find(preference => preference.categoryId === 'charts'); return charts && charts.notificationCadence === 'weekly'; }); const notification = await openMenuItem('[data-testid=tutorial-compact-notification-channel]'); notification.click(); await waitFor(async () => { await viewer.updateComplete; const charts = viewer.snapshot.preferences.find(preference => preference.categoryId === 'charts'); return charts && charts.channel === 'vscodeNotification'; }); return viewer.snapshot.preferences.find(preference => preference.categoryId === 'charts'); })()" in the webview for 20 seconds
    And I evaluate "(async () => { const sleep = ms => new Promise(resolve => setTimeout(resolve, ms)); const waitFor = async predicate => { for (let attempt = 0; attempt < 100; attempt++) { const value = await predicate(); if (value) return value; await sleep(100); } throw new Error('Timed out muting agent category'); }; const viewer = await waitFor(() => document.querySelector('kw-tutorial-viewer')); const root = viewer.shadowRoot; const categorySelect = await waitFor(() => root.querySelector('[data-testid=tutorial-category-select]')); categorySelect.dispatchEvent(new CustomEvent('dropdown-select', { detail: { id: 'all' }, bubbles: true, composed: true })); await viewer.updateComplete; const agentTutorialId = viewer.snapshot.catalog.content.find(tutorial => tutorial.categoryId === 'agent')?.id; const agentButton = await waitFor(() => root.querySelector('[data-tutorial-id=' + agentTutorialId + ']')); agentButton.click(); await waitFor(async () => { await viewer.updateComplete; return viewer.selectedTutorialId === agentTutorialId; }); root.querySelector('[data-testid=tutorial-standard-mute]').click(); await viewer.updateComplete; const agentNotification = await waitFor(() => root.querySelector('[data-testid=tutorial-compact-notification-channel]')); agentNotification.click(); await waitFor(async () => { await viewer.updateComplete; const agent = viewer.snapshot.preferences.find(preference => preference.categoryId === 'agent'); return agent && agent.channel === 'vscodeNotification'; }); root.querySelector('[data-testid=tutorial-standard-mute]').click(); await viewer.updateComplete; const categoriesButton = await waitFor(() => root.querySelector('[data-testid=tutorial-compact-mute-categories]')); categoriesButton.click(); await viewer.updateComplete; const agentMute = await waitFor(() => root.querySelector('[data-testid=tutorial-compact-mute-category-agent]')); agentMute.click(); await waitFor(async () => { await viewer.updateComplete; const agent = viewer.snapshot.preferences.find(preference => preference.categoryId === 'agent'); return agent && agent.channel === 'off' && agent.muted === true; }); const visibleIds = Array.from(root.querySelectorAll('[data-testid=tutorial-item]')).map(button => button.dataset.tutorialId); const agentVisible = visibleIds.some(id => viewer.snapshot.catalog.content.find(tutorial => tutorial.id === id)?.categoryId === 'agent'); const chartsVisible = visibleIds.some(id => viewer.snapshot.catalog.content.find(tutorial => tutorial.id === id)?.categoryId === 'charts'); if (agentVisible) throw new Error('Agent tutorials remained visible after muting the agent category'); if (!chartsVisible) throw new Error('Charts tutorials disappeared when only agent was muted'); return viewer.snapshot.preferences.find(preference => preference.categoryId === 'agent'); })()" in the webview for 20 seconds
    And I evaluate "(async () => { const sleep = ms => new Promise(resolve => setTimeout(resolve, ms)); const waitFor = async predicate => { for (let attempt = 0; attempt < 100; attempt++) { const value = await predicate(); if (value) return value; await sleep(100); } throw new Error('Timed out unmuting agent category'); }; const viewer = await waitFor(() => document.querySelector('kw-tutorial-viewer')); const root = viewer.shadowRoot; const openCategorySubmenu = async () => { const existing = root.querySelector('[data-testid=tutorial-compact-mute-category-agent]'); if (existing) return existing; const menuButton = await waitFor(() => root.querySelector('[data-testid=tutorial-standard-mute]')); menuButton.click(); await viewer.updateComplete; const categoriesButton = await waitFor(() => root.querySelector('[data-testid=tutorial-compact-mute-categories]')); categoriesButton.click(); await viewer.updateComplete; return waitFor(() => root.querySelector('[data-testid=tutorial-compact-mute-category-agent]')); }; const agentUnmute = await openCategorySubmenu(); agentUnmute.click(); await waitFor(async () => { await viewer.updateComplete; const agent = viewer.snapshot.preferences.find(preference => preference.categoryId === 'agent'); return agent && agent.channel === 'vscodeNotification' && agent.muted !== true; }); const agentTutorialId = viewer.snapshot.catalog.content.find(tutorial => tutorial.categoryId === 'agent')?.id; if (!root.querySelector('[data-tutorial-id=' + agentTutorialId + ']')) throw new Error('Agent tutorial did not return after unmuting category'); return viewer.snapshot.preferences.find(preference => preference.categoryId === 'agent'); })()" in the webview for 20 seconds
    And I evaluate "(async () => { const sleep = ms => new Promise(resolve => setTimeout(resolve, ms)); const waitFor = async predicate => { for (let attempt = 0; attempt < 100; attempt++) { const value = await predicate(); if (value) return value; await sleep(100); } throw new Error('Timed out editing agent cadence and delivery'); }; const viewer = await waitFor(() => document.querySelector('kw-tutorial-viewer')); const root = viewer.shadowRoot; const agentTutorialId = viewer.snapshot.catalog.content.find(tutorial => tutorial.categoryId === 'agent')?.id; const agentButton = await waitFor(() => root.querySelector('[data-tutorial-id=' + agentTutorialId + ']')); agentButton.click(); await waitFor(async () => { await viewer.updateComplete; return viewer.selectedTutorialId === agentTutorialId; }); const openMenuItem = async selector => { const existing = root.querySelector(selector); if (existing) return existing; const menuButton = await waitFor(() => root.querySelector('[data-testid=tutorial-standard-mute]')); menuButton.click(); await viewer.updateComplete; return waitFor(() => root.querySelector(selector)); }; const monthly = await openMenuItem('[data-testid=tutorial-compact-cadence-monthly]'); monthly.click(); await waitFor(async () => { await viewer.updateComplete; const agent = viewer.snapshot.preferences.find(preference => preference.categoryId === 'agent'); return agent && agent.notificationCadence === 'monthly'; }); const notification = await openMenuItem('[data-testid=tutorial-compact-notification-channel]'); notification.click(); await waitFor(async () => { await viewer.updateComplete; const agent = viewer.snapshot.preferences.find(preference => preference.categoryId === 'agent'); return agent && agent.channel === 'vscodeNotification'; }); return viewer.snapshot.preferences.find(preference => preference.categoryId === 'agent'); })()" in the webview for 20 seconds
    And I evaluate "(() => { const viewer = document.querySelector('kw-tutorial-viewer'); const charts = viewer.snapshot.preferences.find(preference => preference.categoryId === 'charts'); if (!charts || charts.channel !== 'vscodeNotification' || charts.notificationCadence !== 'weekly') throw new Error('Charts preference changed while editing agent: ' + JSON.stringify(charts)); return charts; })()" in the webview for 5 seconds
    Then I take a screenshot "03-category-cadence-delivery"

  Scenario: Mute everything from the UI disables all delivery controls on reopen
    When I execute command "kusto.openTutorials"
    And I wait for "kw-tutorial-viewer" in the webview for 25 seconds
    And I evaluate "(async () => { const sleep = ms => new Promise(resolve => setTimeout(resolve, ms)); const waitFor = async predicate => { for (let attempt = 0; attempt < 120; attempt++) { const value = await predicate(); if (value) return value; await sleep(100); } throw new Error('Timed out waiting to mute everything from UI'); }; const viewer = await waitFor(() => document.querySelector('kw-tutorial-viewer')); const root = viewer.shadowRoot; await waitFor(async () => { await viewer.updateComplete; return viewer.snapshot && viewer.snapshot.tutorialsEnabled === true && root.querySelector('[data-testid=tutorial-standard-mute]'); }); root.querySelector('[data-testid=tutorial-standard-mute]').click(); await viewer.updateComplete; const muteAll = await waitFor(() => root.querySelector('[data-testid=tutorial-compact-mute-all]')); muteAll.click(); return true; })()" in the webview for 25 seconds
    And I wait 2 seconds
    When I execute command "kusto.openTutorials"
    And I wait for "kw-tutorial-viewer" in the webview for 25 seconds
    And I evaluate "(async () => { const sleep = ms => new Promise(resolve => setTimeout(resolve, ms)); const waitFor = async predicate => { for (let attempt = 0; attempt < 120; attempt++) { const value = await predicate(); if (value) return value; await sleep(100); } throw new Error('Timed out waiting for UI-muted disabled state'); }; const viewer = await waitFor(() => document.querySelector('kw-tutorial-viewer')); const root = viewer.shadowRoot; await waitFor(async () => { await viewer.updateComplete; return viewer.snapshot && viewer.snapshot.tutorialsEnabled === false && root.querySelector('[data-testid=tutorial-standard-mute]'); }); root.querySelector('[data-testid=tutorial-standard-mute]').click(); await viewer.updateComplete; await waitFor(() => root.querySelector('[data-testid=tutorial-compact-unmute-all]')); const enabledButtons = Array.from(root.querySelectorAll('.mute-menu button')).filter(button => !button.disabled).map(button => button.dataset.testid); if (enabledButtons.join(',') !== 'tutorial-compact-unmute-all') throw new Error('UI mute everything should match disabled setting, got enabled buttons ' + enabledButtons.join(',')); return { tutorialsEnabled: viewer.snapshot.tutorialsEnabled, enabledButtons }; })()" in the webview for 25 seconds
    Then I take a screenshot "04-ui-muted-all"