Feature: Connection Manager edge states

  Background:
    Given the extension is in a clean state
    And I capture the output channel "Kusto Workbench"
    And I wait 2 seconds

  Scenario: Connection Manager handles uncached and failed schema states
    When I execute command "kusto.manageConnections"
    And I wait 3 seconds
    When I wait for "kw-connection-manager" in the webview for 20 seconds

    When I evaluate "(() => { const snapshot = { timestamp: Date.now(), activeKind: 'kusto', connections: [{ id: 'fake-kusto', name: 'Broken Cluster', clusterUrl: 'https://broken.kusto.windows.net' }], favorites: [], cachedDatabases: {}, expandedClusters: [], leaveNoTraceClusters: [], sqlConnections: [{ id: 'sql-edge', name: 'Broken SQL', dialect: 'mssql', serverUrl: 'broken.database.windows.net', authType: 'aad' }], sqlCachedDatabases: { 'sql-edge': [] }, sqlExpandedConnections: [], sqlFavorites: [], sqlLeaveNoTrace: [] }; window.dispatchEvent(new MessageEvent('message', { data: { type: 'snapshot', snapshot } })); return 'seeded empty Kusto snapshot'; })()" in the webview
    And I wait 1 second

    When I evaluate "(() => { const snapshot = { timestamp: Date.now(), activeKind: 'kusto', connections: [{ id: 'empty-kusto', name: 'Empty Cluster', clusterUrl: 'https://empty.kusto.windows.net' }], favorites: [], cachedDatabases: { 'empty.kusto.windows.net': [] }, expandedClusters: ['empty-kusto'], leaveNoTraceClusters: [], sqlConnections: [], sqlCachedDatabases: {}, sqlExpandedConnections: [], sqlFavorites: [], sqlLeaveNoTrace: [] }; window.dispatchEvent(new MessageEvent('message', { data: { type: 'snapshot', snapshot } })); const root = document.querySelector('kw-connection-manager')?.shadowRoot; const row = [...root.querySelectorAll('.explorer-list-item')].find(item => item.textContent.includes('Empty Cluster')); if (!row) throw new Error('Empty Cluster row missing'); row.click(); const empty = root.querySelector('[data-testid=cm-database-empty-state]'); if (!empty) throw new Error('Kusto database empty state missing; cluster body is blank'); const text = empty.textContent || ''; if (!text.includes('No databases found') || !text.includes('Refresh')) throw new Error('Unexpected empty database text: ' + text); return 'Kusto empty database state is visible'; })()" in the webview

    When I evaluate "(() => { const cm = document.querySelector('kw-connection-manager'); const root = cm?.shadowRoot; const row = [...root.querySelectorAll('.explorer-list-item')].find(item => item.textContent.includes('Broken Cluster')); if (!row) throw new Error('Broken Cluster row missing'); row.click(); window.dispatchEvent(new MessageEvent('message', { data: { type: 'databasesLoadError', connectionId: 'fake-kusto', error: 'Authentication required for edge probe' } })); const err = root.querySelector('[data-testid=cm-database-load-error]'); if (!err) throw new Error('Kusto database load error state missing'); const text = err.textContent || ''; if (!text.includes('Could not load databases') || !text.includes('Authentication required for edge probe')) throw new Error('Unexpected Kusto database error text: ' + text); const messages = []; const original = cm._vscode.postMessage.bind(cm._vscode); cm._vscode.postMessage = message => { messages.push(message); }; try { err.querySelector('button')?.click(); } finally { cm._vscode.postMessage = original; } if (!messages.some(message => message.type === 'cluster.refreshDatabases' && message.connectionId === 'fake-kusto')) throw new Error('Kusto database retry did not post cluster.refreshDatabases: ' + JSON.stringify(messages)); return 'Kusto database load error shows retry'; })()" in the webview

    When I evaluate "(() => { const snapshot = { timestamp: Date.now(), activeKind: 'kusto', connections: [{ id: 'fake-kusto', name: 'Broken Cluster', clusterUrl: 'https://broken.kusto.windows.net' }], favorites: [], cachedDatabases: { 'broken.kusto.windows.net': ['EdgeDb'] }, expandedClusters: ['fake-kusto'], leaveNoTraceClusters: [], sqlConnections: [], sqlCachedDatabases: {}, sqlExpandedConnections: [], sqlFavorites: [], sqlLeaveNoTrace: [] }; window.dispatchEvent(new MessageEvent('message', { data: { type: 'snapshot', snapshot } })); const cm = document.querySelector('kw-connection-manager'); const root = cm?.shadowRoot; const dbRow = [...root.querySelectorAll('.explorer-list-item')].find(item => item.textContent.includes('EdgeDb')); if (!dbRow) throw new Error('EdgeDb row missing after cached snapshot'); dbRow.click(); window.dispatchEvent(new MessageEvent('message', { data: { type: 'schemaLoadError', connectionId: 'fake-kusto', database: 'EdgeDb', error: 'Schema cache miss probe failed' } })); const err = root.querySelector('[data-testid=cm-schema-load-error]'); if (!err) throw new Error('Kusto schema load error state missing'); const text = err.textContent || ''; if (!text.includes('Could not load schema') || !text.includes('Schema cache miss probe failed')) throw new Error('Unexpected Kusto schema error text: ' + text); const messages = []; const original = cm._vscode.postMessage.bind(cm._vscode); cm._vscode.postMessage = message => { messages.push(message); }; try { err.querySelector('button')?.click(); } finally { cm._vscode.postMessage = original; } if (!messages.some(message => message.type === 'database.getSchema' && message.connectionId === 'fake-kusto' && message.database === 'EdgeDb')) throw new Error('Kusto schema retry did not post database.getSchema: ' + JSON.stringify(messages)); return 'Kusto schema load error shows retry'; })()" in the webview

    When I evaluate "(() => { const snapshot = { timestamp: Date.now(), activeKind: 'sql', connections: [], favorites: [], cachedDatabases: {}, expandedClusters: [], leaveNoTraceClusters: [], sqlConnections: [{ id: 'sql-edge', name: 'Broken SQL', dialect: 'mssql', serverUrl: 'broken.database.windows.net', authType: 'aad' }], sqlCachedDatabases: { 'sql-edge': [] }, sqlExpandedConnections: [], sqlFavorites: [], sqlLeaveNoTrace: [] }; window.dispatchEvent(new MessageEvent('message', { data: { type: 'snapshot', snapshot } })); const cm = document.querySelector('kw-connection-manager'); const root = cm?.shadowRoot; const row = [...root.querySelectorAll('.explorer-list-item')].find(item => item.textContent.includes('Broken SQL')); if (!row) throw new Error('Broken SQL row missing'); row.click(); window.dispatchEvent(new MessageEvent('message', { data: { type: 'sql.databasesLoadError', connectionId: 'sql-edge', error: 'SQL login failed for edge probe' } })); const err = root.querySelector('[data-testid=cm-sql-database-load-error]'); if (!err) throw new Error('SQL database load error state missing'); const text = err.textContent || ''; if (!text.includes('Could not load databases') || !text.includes('SQL login failed for edge probe')) throw new Error('Unexpected SQL database error text: ' + text); const messages = []; const original = cm._vscode.postMessage.bind(cm._vscode); cm._vscode.postMessage = message => { messages.push(message); }; try { err.querySelector('button')?.click(); } finally { cm._vscode.postMessage = original; } if (!messages.some(message => message.type === 'sql.cluster.refreshDatabases' && message.connectionId === 'sql-edge')) throw new Error('SQL database retry did not post sql.cluster.refreshDatabases: ' + JSON.stringify(messages)); return 'SQL database load error shows retry'; })()" in the webview

    When I evaluate "(() => { const snapshot = { timestamp: Date.now(), activeKind: 'sql', connections: [], favorites: [], cachedDatabases: {}, expandedClusters: [], leaveNoTraceClusters: [], sqlConnections: [{ id: 'sql-edge', name: 'Broken SQL', dialect: 'mssql', serverUrl: 'broken.database.windows.net', authType: 'aad' }], sqlCachedDatabases: { 'sql-edge': ['SqlEdgeDb'] }, sqlExpandedConnections: ['sql-edge'], sqlFavorites: [], sqlLeaveNoTrace: [] }; window.dispatchEvent(new MessageEvent('message', { data: { type: 'snapshot', snapshot } })); const cm = document.querySelector('kw-connection-manager'); const root = cm?.shadowRoot; const dbRow = [...root.querySelectorAll('.explorer-list-item')].find(item => item.textContent.includes('SqlEdgeDb')); if (!dbRow) throw new Error('SqlEdgeDb row missing after cached SQL snapshot'); dbRow.click(); window.dispatchEvent(new MessageEvent('message', { data: { type: 'sql.schemaLoadError', connectionId: 'sql-edge', database: 'SqlEdgeDb', error: 'SQL schema unavailable for edge probe' } })); const err = root.querySelector('[data-testid=cm-sql-schema-load-error]'); if (!err) throw new Error('SQL schema load error state missing'); const text = err.textContent || ''; if (!text.includes('Could not load schema') || !text.includes('SQL schema unavailable for edge probe')) throw new Error('Unexpected SQL schema error text: ' + text); const messages = []; const original = cm._vscode.postMessage.bind(cm._vscode); cm._vscode.postMessage = message => { messages.push(message); }; try { err.querySelector('button')?.click(); } finally { cm._vscode.postMessage = original; } if (!messages.some(message => message.type === 'sql.database.getSchema' && message.connectionId === 'sql-edge' && message.database === 'SqlEdgeDb')) throw new Error('SQL schema retry did not post sql.database.getSchema: ' + JSON.stringify(messages)); return 'SQL schema load error shows retry'; })()" in the webview
