Feature: Live Kusto Authority ID guest-tenant authentication

  Background:
    Given the extension is in a clean state
    And I capture the output channel "Kusto Workbench"
    When I execute command "kusto.manageConnections"
    And I wait 2 seconds
    When I move the Dev Host to 0, 0
    When I resize the Dev Host to 1280x1000
    When I execute command "workbench.action.closeAuxiliaryBar"

  Scenario: Same account sees the target database only through the resource authority
    Then I collect JSON artifact "authority-live-result" from extension host expression "(async () => { const result = await vscode.commands.executeCommand('kustoWorkbench.test.runAuthorityLiveFixture'); if (!result?.verified || result.wrongTargetVisible || !result.resourceTargetVisible) throw new Error('Authority fixture contract failed: ' + JSON.stringify(result)); return result; })()"

    When I execute command "kusto.manageConnections"
    When I wait for "[data-testid='cm-kusto-connection-row']" in the webview "Connection Manager" for 20 seconds
    When I evaluate "(() => { const root = document.querySelector('kw-connection-manager')?.shadowRoot; const rows = Array.from(root?.querySelectorAll('[data-testid=cm-kusto-connection-row]') || []).filter(row => row.querySelector('.explorer-list-item-name')?.textContent?.trim().startsWith('E2E Authority ID Live')); if (rows.length !== 2) throw new Error('Expected two Authority ID fixture connections, got ' + rows.length); const urls = new Set(rows.map(row => row.querySelector('.explorer-list-item-url')?.textContent?.trim())); const tenants = new Set(rows.map(row => Array.from(row.querySelectorAll('.explorer-list-item-meta')).map(node => node.textContent?.trim()).find(text => text?.startsWith('Tenant: ')))); if (urls.size !== 1) throw new Error('Fixture connections do not share one endpoint'); if (tenants.size !== 2 || tenants.has(undefined)) throw new Error('Expected two distinct tenant labels: ' + JSON.stringify(Array.from(tenants))); const resourceRow = rows.find(row => row.querySelector('.explorer-list-item-name')?.textContent?.includes('Resource authority')); const edit = resourceRow?.querySelector('button[title=Edit]'); if (!edit) throw new Error('Resource authority Edit action not found'); edit.click(); return { sharedEndpoint: Array.from(urls)[0], tenants: Array.from(tenants) }; })()" in the webview "Connection Manager"
    When I evaluate "(async () => { const root = document.querySelector('kw-connection-manager')?.shadowRoot; const form = root?.querySelector('[data-testid=cm-modal-content] kw-kusto-connection-form'); await form?.updateComplete; await new Promise(resolve => requestAnimationFrame(() => resolve())); const authority = form?.shadowRoot?.querySelector('[data-testid=kusto-conn-authority-id]'); const account = form?.shadowRoot?.querySelector('[data-testid=kusto-conn-account]'); const selectedAccount = account?.selectedOptions?.[0]?.textContent?.trim() || ''; if (!authority?.value) throw new Error('Resource authority was not loaded into the visible edit form'); if (!account?.value || !selectedAccount || selectedAccount === 'Automatic') throw new Error('Visible edit form did not select the configured explicit account: value=' + account?.value + ' text=' + selectedAccount); return { authorityConfigured: true, accountConfigured: true, selectedAccount }; })()" in the webview "Connection Manager"
    When I execute command "workbench.action.focusActiveEditorGroup"
    Then I take a screenshot "01-authority-connection-edit"

    When I execute command "kusto.seeCachedValues"
    When I wait for "[data-testid='cv-kusto-connection-auth-row']" in the webview "Cached Values" for 20 seconds
    When I evaluate "(async () => { const root = document.querySelector('kw-cached-values')?.shadowRoot; const rows = Array.from(root?.querySelectorAll('[data-testid=cv-kusto-connection-auth-row]') || []).filter(row => row.querySelector('td')?.textContent?.trim().startsWith('E2E Authority ID Live')); if (rows.length !== 2) throw new Error('Expected two Authority ID rows in Cached Values, got ' + rows.length); const authorities = new Set(rows.map(row => row.querySelectorAll('td')[1]?.textContent?.trim())); if (authorities.size !== 2) throw new Error('Cached Values did not preserve distinct authorities'); const selectedAccounts = rows.map(row => row.querySelector('select')?.selectedOptions?.[0]?.textContent?.trim() || ''); if (rows.some(row => !row.querySelector('select')?.value) || selectedAccounts.some(account => !account || account === 'Automatic') || new Set(selectedAccounts).size !== 1) throw new Error('A fixture connection lost the configured explicit account selection: ' + JSON.stringify(selectedAccounts)); rows[0].scrollIntoView({ block: 'center' }); await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))); return { rows: rows.length, authorities: Array.from(authorities), selectedAccounts }; })()" in the webview "Cached Values"
    Then I take a screenshot "02-authority-cached-values"

    When I execute command "kustoWorkbench.test.cleanupAuthorityLiveFixture"

  Scenario: Guest connection created through Add Connection sees the resource database
    When I execute command "kustoWorkbench.test.cleanupKustoIdentityChecklist"
    When I execute command "kusto.manageConnections"
    When I wait for "[data-testid='cm-add-connection']" in the webview "Connection Manager" for 20 seconds
    When I evaluate "(async () => { const root = document.querySelector('kw-connection-manager')?.shadowRoot; root?.querySelector('[data-testid=cm-add-connection]')?.click(); await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))); const form = root?.querySelector('[data-testid=cm-modal-content] kw-kusto-connection-form'); if (!form) throw new Error('Guest Add Connection form did not open'); const formRoot = form.shadowRoot; const setInput = (id, value) => { const input = formRoot.querySelector('[data-testid=' + id + ']'); if (!input) throw new Error('Missing ' + id); input.value = value; input.dispatchEvent(new Event('input', { bubbles: true, composed: true })); }; setInput('kusto-conn-name', 'E2E Identity Checklist Guest UI'); setInput('kusto-conn-cluster-url', 'https://kwtenantrepro705.eastus.kusto.windows.net'); setInput('kusto-conn-database', 'TenantReproDb'); setInput('kusto-conn-authority-id', '910c7523-ebb8-4411-871e-1593f3c37767'); const account = formRoot.querySelector('[data-testid=kusto-conn-account]'); const explicit = Array.from(account?.options || []).find(option => option.value); if (!explicit) throw new Error('Prepared profile has no Microsoft account option'); account.value = explicit.value; account.dispatchEvent(new Event('change', { bubbles: true, composed: true })); root.querySelector('[data-testid=cm-modal-content] .modal-footer .btn.primary')?.click(); const deadline = Date.now() + 15000; while (Date.now() < deadline) { const row = Array.from(root.querySelectorAll('[data-testid=cm-kusto-connection-row]')).find(candidate => candidate.querySelector('.explorer-list-item-name')?.textContent?.trim() === 'E2E Identity Checklist Guest UI'); if (row && !root.querySelector('[data-testid=cm-modal-overlay]')) { const tenant = Array.from(row.querySelectorAll('.explorer-list-item-meta')).map(node => node.textContent?.trim()).find(text => text?.startsWith('Tenant: ')); if (tenant !== 'Tenant: 910c7523-ebb8-4411-871e-1593f3c37767') throw new Error('Guest authority was not persisted: ' + tenant); return { saved: true, account: explicit.textContent?.trim(), tenant }; } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Guest connection was not persisted through Add/Save'); })()" in the webview "Connection Manager" for 20 seconds
    When I evaluate "(async () => { const root = document.querySelector('kw-connection-manager')?.shadowRoot; const row = Array.from(root?.querySelectorAll('[data-testid=cm-kusto-connection-row]') || []).find(candidate => candidate.querySelector('.explorer-list-item-name')?.textContent?.trim() === 'E2E Identity Checklist Guest UI'); if (!row) throw new Error('Saved guest row missing'); const connectionId = row.getAttribute('data-connection-id'); const edit = row.querySelector('button[title=Edit]'); edit?.click(); await new Promise(resolve => requestAnimationFrame(() => resolve())); const form = root.querySelector('[data-testid=cm-modal-content] kw-kusto-connection-form'); const authority = form?.shadowRoot?.querySelector('[data-testid=kusto-conn-authority-id]'); const account = form?.shadowRoot?.querySelector('[data-testid=kusto-conn-account]'); if (authority?.value !== '910c7523-ebb8-4411-871e-1593f3c37767') throw new Error('Edit form lost guest authority'); if (!account?.value || account?.selectedOptions?.[0]?.textContent?.trim() === 'Automatic') throw new Error('Edit form lost explicit account'); root.querySelector('[data-testid=cm-modal-content] .modal-footer button')?.click(); row.click(); const deadline = Date.now() + 60000; while (Date.now() < deadline) { const error = root.querySelector('.empty-state-error, .error-message')?.textContent?.trim(); if (error) throw new Error('Guest database discovery failed: ' + error); const databaseRows = Array.from(root.querySelectorAll('.explorer-list-item')).filter(item => item.querySelector('.explorer-list-item-icon.database')); const database = databaseRows.find(item => item.querySelector('.explorer-list-item-name')?.textContent?.trim() === 'TenantReproDb'); if (database && connectionId && !root.querySelector('.loading-indicator')) return { databaseVisible: true, database: 'TenantReproDb', connectionId }; await new Promise(resolve => setTimeout(resolve, 250)); } throw new Error('Guest connection did not reveal a loaded TenantReproDb row after Add/Save'); })()" in the webview "Connection Manager" for 65 seconds
    When I execute command "workbench.action.focusActiveEditorGroup"
    Then I take a screenshot "03-guest-ui-database-visible"
    When I execute command "kustoWorkbench.test.cleanupKustoIdentityChecklist"