Feature: Did you know disabled setting

  Background:
    Given the extension is in a clean state
    When I move the Dev Host to 0, 0
    And I resize the Dev Host to 1200 by 900
    And I execute command "workbench.action.closeSidebar"
    And I execute command "workbench.action.closeAuxiliaryBar"
    And I execute command "workbench.action.closePanel"
    And I capture the output channel "Kusto Workbench"
    And I wait 2 seconds

  Scenario: Main Did you know setting disables all delivery controls
    When I execute command "kusto.openTutorials"
    And I wait for "kw-tutorial-viewer" in the webview for 25 seconds
    And I evaluate "(async () => { const sleep = ms => new Promise(resolve => setTimeout(resolve, ms)); const waitFor = async predicate => { for (let attempt = 0; attempt < 120; attempt++) { const value = await predicate(); if (value) return value; await sleep(100); } throw new Error('Timed out waiting for disabled Did you know state'); }; const viewer = await waitFor(() => document.querySelector('kw-tutorial-viewer')); const root = viewer.shadowRoot; await waitFor(async () => { await viewer.updateComplete; return viewer.snapshot && root.querySelector('[data-testid=tutorial-viewer-mode-standard]') && root.querySelector('[data-testid=tutorial-standard-mute]'); }); if (viewer.snapshot.tutorialsEnabled !== false) throw new Error('snapshot.tutorialsEnabled was not false'); root.querySelector('[data-testid=tutorial-standard-mute]').click(); await viewer.updateComplete; await waitFor(() => root.querySelector('[data-testid=tutorial-compact-unmute-all]')); const enabledButtons = Array.from(root.querySelectorAll('.mute-menu button')).filter(button => !button.disabled).map(button => button.dataset.testid); if (enabledButtons.join(',') !== 'tutorial-compact-unmute-all') throw new Error('Disabled state should leave only Unmute everything enabled, got ' + enabledButtons.join(',')); return { tutorialsEnabled: viewer.snapshot.tutorialsEnabled, enabledButtons }; })()" in the webview for 25 seconds
    Then I take a screenshot "01-disabled-setting-open"
    And I evaluate "(() => { const viewer = document.querySelector('kw-tutorial-viewer'); if (!viewer) throw new Error('kw-tutorial-viewer not found'); const root = viewer.shadowRoot; if (!root.querySelector('[data-testid=tutorial-compact-unmute-all]')) root.querySelector('[data-testid=tutorial-standard-mute]')?.click(); const unmuteAll = root.querySelector('[data-testid=tutorial-compact-unmute-all]'); if (!unmuteAll) throw new Error('Unmute everything was not available after reopening the menu'); unmuteAll.click(); return { clicked: true, tutorialsEnabledBeforeClick: viewer.snapshot?.tutorialsEnabled }; })()" in the webview for 5 seconds
    And I wait 2 seconds
    And I evaluate "(async () => { const sleep = ms => new Promise(resolve => setTimeout(resolve, ms)); const viewer = document.querySelector('kw-tutorial-viewer'); if (!viewer) throw new Error('kw-tutorial-viewer not found'); for (let attempt = 0; attempt < 80; attempt++) { if (viewer.snapshot?.tutorialsEnabled === true) return { tutorialsEnabled: viewer.snapshot.tutorialsEnabled }; await sleep(100); } throw new Error('Unmute everything did not enable Did you know; snapshot=' + JSON.stringify(viewer.snapshot)); })()" in the webview for 10 seconds
    And I evaluate "(async () => { const sleep = ms => new Promise(resolve => setTimeout(resolve, ms)); const waitFor = async predicate => { for (let attempt = 0; attempt < 80; attempt++) { const value = await predicate(); if (value) return value; await sleep(100); } throw new Error('Timed out waiting for enabled delivery controls'); }; const viewer = document.querySelector('kw-tutorial-viewer'); const root = viewer.shadowRoot; root.querySelector('[data-testid=tutorial-standard-mute]').click(); const muteAll = await waitFor(() => root.querySelector('[data-testid=tutorial-compact-mute-all]')); const enabledButtons = Array.from(root.querySelectorAll('.mute-menu button')).filter(button => !button.disabled).map(button => button.dataset.testid); if (!enabledButtons.includes('tutorial-compact-popup-channel') || !enabledButtons.includes('tutorial-compact-notification-channel') || !enabledButtons.includes('tutorial-compact-mute-all')) throw new Error('Unmute everything did not re-enable delivery controls, got ' + enabledButtons.join(',')); return { muteAll: Boolean(muteAll), tutorialsEnabled: viewer.snapshot.tutorialsEnabled, enabledButtons }; })()" in the webview for 10 seconds
    Then I take a screenshot "02-disabled-setting-unmuted"