Feature: Run All results survive session close and reopen

  Background:
    Given the extension is in a clean state
    And I capture the output channel "Kusto Workbench"
    When I move the Dev Host to 0, 0
    And I resize the Dev Host to 1280x1000
    And I execute command "workbench.action.closeAuxiliaryBar"

  Scenario: Sticky Run All persists selected results without an explicit Save
    When I execute command "kustoWorkbench.test.closeQueryEditorSession"
    And I execute command "kusto.openQueryEditor"
    And I wait 5 seconds
    When I wait for "#queries-container" in the webview "session.kqlx" for 20 seconds
    When I evaluate "(async () => { await window.__e2e.workbench.clearSections(); const nl = String.fromCharCode(10); const query = ['print ResultSet = \'first\', Value = 1', ';', 'print ResultSet = \'second\', Value = 2', ';', 'print ResultSet = \'third\', Value = 3'].join(nl); const id = window.addQueryBox({ id: 'query_session_run_all', name: 'Session Run All', initialQuery: query, expanded: true }); const section = document.getElementById(id); const connection = (window.connections || []).find(candidate => String(candidate.clusterUrl || '').includes('1es.kusto.windows.net')); if (!section || !connection) throw new Error('Authenticated 1es connection is unavailable'); section.setConnections(window.connections || []); section.setConnectionId(connection.id); section.setDatabase('Liquid'); section.setFavorites([{ connectionId: connection.id, clusterUrl: connection.clusterUrl, database: 'Liquid', name: 'Runtime-only favorite' }]); section.setFavoritesMode(true); section.setPersistConnectionSelection(false); section.setSchemaLifecycleTarget(connection.id, 'Liquid'); window.__kustoUpdateRunEnabledForBox?.(id); const serialized = section.serialize(); if (serialized.clusterUrl || serialized.database || serialized.connectionIdHint) throw new Error('Runtime-only target unexpectedly became authored: ' + JSON.stringify(serialized)); window.schedulePersist?.('e2e-session-run-all-setup', true); return id; })()" in the webview "session.kqlx" for 20 seconds
    When I wait for "#query_session_run_all[data-test-connection='true']" in the webview "session.kqlx" for 60 seconds
    When I wait for "#query_session_run_all[data-test-database-selected='true']" in the webview "session.kqlx" for 60 seconds
    And I wait 1 second

    When I evaluate "window.__e2e.kusto.selectRunMode('runAll')" in the webview "session.kqlx"
    When I wait for "#query_session_run_all[data-test-executing='false'][data-test-has-results='true']" in the webview "session.kqlx" for 60 seconds
    When I wait for "[data-testid='result-set-picker']" in the webview "session.kqlx" for 10 seconds
    When I evaluate "(() => { const table = document.getElementById('query_session_run_all')?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); if (!picker) throw new Error('Result picker is unavailable'); picker.value = '2'; picker.dispatchEvent(new Event('change', { bubbles: true, composed: true })); return 'requested Result 3'; })()" in the webview "session.kqlx"
    When I evaluate "(async () => { const deadline = Date.now() + 10000; const raw = value => value && typeof value === 'object' ? value.full ?? value.display : value; while (Date.now() < deadline) { const section = document.getElementById('query_session_run_all'); const table = section?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); const columns = (table?.columns || []).map(column => typeof column === 'string' ? column : column.name); const row = table?.rows?.[0] || []; if (picker?.value === '2' && table?.options?.selectedResultIndex === 2 && raw(row[columns.indexOf('ResultSet')]) === 'third' && Number(raw(row[columns.indexOf('Value')])) === 3) return 'Result 3 accepted'; await new Promise(resolve => setTimeout(resolve, 50)); } throw new Error('Result 3 selection was not accepted before close'); })()" in the webview "session.kqlx" for 15 seconds
    When I execute command "workbench.action.closeAllEditors"
    And I wait 2 seconds

    When I execute command "kusto.openQueryEditor"
    And I wait 5 seconds
    When I wait for "#query_session_run_all" in the webview "session.kqlx" for 20 seconds
    When I evaluate "window.__e2e.workbench.waitForPersistedResult('query_session_run_all', 19000)" in the webview "session.kqlx" for 20 seconds
    Then I collect JSON artifact "reopened-menu-run-all-result-three" from webview expression "(() => { const raw = value => value && typeof value === 'object' ? value.full ?? value.display : value; const section = document.getElementById('query_session_run_all'); const serialized = section?.serialize?.(); const batch = serialized?.resultJson ? JSON.parse(serialized.resultJson) : undefined; const table = section?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); const options = [...(picker?.options || [])].map(option => option.textContent); const mode = window.runModesByBoxId?.query_session_run_all; const columns = (table?.columns || []).map(column => typeof column === 'string' ? column : column.name); const row = table?.rows?.[0] || []; const resultSetCount = batch ? 1 + (batch.additionalResults?.sets?.length || 0) : 0; if (!table || options.length !== 3 || resultSetCount !== 3 || mode !== 'runAll' || picker?.value !== '2' || table.options?.selectedResultIndex !== 2 || !serialized.clusterUrl?.includes('1es.kusto.windows.net') || serialized.database !== 'Liquid' || !serialized.connectionIdHint || raw(row[columns.indexOf('ResultSet')]) !== 'third' || Number(raw(row[columns.indexOf('Value')])) !== 3) throw new Error('Reopened menu Run All Result 3 is missing: ' + JSON.stringify({ options, resultSetCount, mode, picker: picker?.value, selectedResultIndex: table?.options?.selectedResultIndex, clusterUrl: serialized?.clusterUrl, database: serialized?.database, connectionIdHint: serialized?.connectionIdHint, columns, row })); return { options, resultSetCount, mode, selectedResultIndex: table.options.selectedResultIndex, clusterUrl: serialized.clusterUrl, database: serialized.database, connectionIdHint: serialized.connectionIdHint, row: row.map(raw) }; })()"
    When I click "[data-testid='result-set-picker']" in the webview "session.kqlx"
    When I press "ArrowUp"
    When I press "Enter"
    When I evaluate "(async () => { const deadline = Date.now() + 10000; const raw = value => value && typeof value === 'object' ? value.full ?? value.display : value; while (Date.now() < deadline) { const section = document.getElementById('query_session_run_all'); const table = section?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); const columns = (table?.columns || []).map(column => typeof column === 'string' ? column : column.name); const row = table?.rows?.[0] || []; if (picker?.value === '1' && table?.options?.selectedResultIndex === 1 && raw(row[columns.indexOf('ResultSet')]) === 'second' && Number(raw(row[columns.indexOf('Value')])) === 2) return 'Result 2 accepted after reopen'; await new Promise(resolve => setTimeout(resolve, 50)); } throw new Error('Could not switch reopened results to Result 2'); })()" in the webview "session.kqlx" for 15 seconds
    Then I collect JSON artifact "reopened-menu-switched-to-result-two" from webview expression "(() => { const raw = value => value && typeof value === 'object' ? value.full ?? value.display : value; const section = document.getElementById('query_session_run_all'); const table = section?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); const columns = (table?.columns || []).map(column => typeof column === 'string' ? column : column.name); const row = table?.rows?.[0] || []; if (picker?.value !== '1' || table?.options?.selectedResultIndex !== 1 || raw(row[columns.indexOf('ResultSet')]) !== 'second' || Number(raw(row[columns.indexOf('Value')])) !== 2) throw new Error('Reopened Result 2 state is incorrect'); return { selectedResultIndex: table.options.selectedResultIndex, row: row.map(raw) }; })()"

    When I evaluate "window.__e2e.kusto.run()" in the webview "session.kqlx"
    When I wait for "#query_session_run_all[data-test-executing='false'][data-test-has-results='true']" in the webview "session.kqlx" for 60 seconds
    When I wait for "[data-testid='result-set-picker']" in the webview "session.kqlx" for 10 seconds
    When I evaluate "(() => { const table = document.getElementById('query_session_run_all')?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); if (!picker) throw new Error('Sticky rerun result picker is unavailable'); picker.value = '2'; picker.dispatchEvent(new Event('change', { bubbles: true, composed: true })); return 'requested Result 3 after sticky rerun'; })()" in the webview "session.kqlx"
    When I evaluate "(async () => { const deadline = Date.now() + 10000; const raw = value => value && typeof value === 'object' ? value.full ?? value.display : value; while (Date.now() < deadline) { const section = document.getElementById('query_session_run_all'); const table = section?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); const columns = (table?.columns || []).map(column => typeof column === 'string' ? column : column.name); const row = table?.rows?.[0] || []; if (picker?.value === '2' && table?.options?.selectedResultIndex === 2 && raw(row[columns.indexOf('ResultSet')]) === 'third' && Number(raw(row[columns.indexOf('Value')])) === 3) return 'Sticky rerun Result 3 accepted'; await new Promise(resolve => setTimeout(resolve, 50)); } throw new Error('Sticky rerun Result 3 selection was not accepted before close'); })()" in the webview "session.kqlx" for 15 seconds
    When I execute command "workbench.action.closeAllEditors"
    And I wait 2 seconds

    When I execute command "kusto.openQueryEditor"
    And I wait 5 seconds
    When I wait for "#query_session_run_all" in the webview "session.kqlx" for 20 seconds
    When I evaluate "window.__e2e.workbench.waitForPersistedResult('query_session_run_all', 19000)" in the webview "session.kqlx" for 20 seconds
    Then I collect JSON artifact "reopened-sticky-run-all-result-three" from webview expression "(() => { const raw = value => value && typeof value === 'object' ? value.full ?? value.display : value; const section = document.getElementById('query_session_run_all'); const serialized = section?.serialize?.(); const batch = serialized?.resultJson ? JSON.parse(serialized.resultJson) : undefined; const table = section?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); const options = [...(picker?.options || [])].map(option => option.textContent); const mode = window.runModesByBoxId?.query_session_run_all; const columns = (table?.columns || []).map(column => typeof column === 'string' ? column : column.name); const row = table?.rows?.[0] || []; const resultSetCount = batch ? 1 + (batch.additionalResults?.sets?.length || 0) : 0; if (!table || options.length !== 3 || resultSetCount !== 3 || mode !== 'runAll' || picker?.value !== '2' || table.options?.selectedResultIndex !== 2 || !serialized.clusterUrl?.includes('1es.kusto.windows.net') || serialized.database !== 'Liquid' || !serialized.connectionIdHint || raw(row[columns.indexOf('ResultSet')]) !== 'third' || Number(raw(row[columns.indexOf('Value')])) !== 3) throw new Error('Reopened sticky Run All Result 3 is missing: ' + JSON.stringify({ options, resultSetCount, mode, picker: picker?.value, selectedResultIndex: table?.options?.selectedResultIndex, clusterUrl: serialized?.clusterUrl, database: serialized?.database, connectionIdHint: serialized?.connectionIdHint, columns, row })); return { options, resultSetCount, mode, selectedResultIndex: table.options.selectedResultIndex, clusterUrl: serialized.clusterUrl, database: serialized.database, connectionIdHint: serialized.connectionIdHint, row: row.map(raw) }; })()"
    When I evaluate "window.__e2e.workbench.forceDocumentReload()" in the webview "session.kqlx" for 15 seconds
    When I evaluate "window.__e2e.workbench.waitForPersistedResult('query_session_run_all', 14000)" in the webview "session.kqlx" for 15 seconds
    Then I collect JSON artifact "reopened-sticky-after-force-reload-result-three" from webview expression "(() => { const raw = value => value && typeof value === 'object' ? value.full ?? value.display : value; const section = document.getElementById('query_session_run_all'); const table = section?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); const columns = (table?.columns || []).map(column => typeof column === 'string' ? column : column.name); const row = table?.rows?.[0] || []; if (picker?.value !== '2' || table?.options?.selectedResultIndex !== 2 || table?.resultArtifactId !== 'result:query_session_run_all:2:set:2' || raw(row[columns.indexOf('ResultSet')]) !== 'third' || Number(raw(row[columns.indexOf('Value')])) !== 3) throw new Error('Force reload did not preserve Result 3 revision 2: ' + JSON.stringify({ picker: picker?.value, selectedResultIndex: table?.options?.selectedResultIndex, artifactId: table?.resultArtifactId, row })); return { selectedResultIndex: table.options.selectedResultIndex, artifactId: table.resultArtifactId, row: row.map(raw) }; })()"
    When I evaluate "(() => { const section = document.getElementById('query_session_run_all'); if (!section) throw new Error('Reopened sticky query section is unavailable'); const applyResponse = section.applyResultSelectionResponse.bind(section); window.__e2eResultSelectionResponses = []; section.applyResultSelectionResponse = message => { window.__e2eResultSelectionResponses.push({ requestId: message.requestId, boxId: message.boxId, primaryArtifactId: message.primaryArtifactId, resultIndex: message.resultIndex, accepted: message.accepted }); return applyResponse(message); }; return 'observing sticky Result 2 selection'; })()" in the webview "session.kqlx"
    When I click "[data-testid='result-set-picker']" in the webview "session.kqlx"
    When I press "ArrowUp"
    When I press "Enter"
    And I wait 2 seconds
    Then I collect JSON artifact "reopened-sticky-result-two-selection-response" from webview expression "(() => { const section = document.getElementById('query_session_run_all'); const table = section?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); const lifecycle = section?.getSchemaLifecycleIdentity?.(); const pending = section?._pendingResultSelection; return { responses: window.__e2eResultSelectionResponses || [], pending: pending ? { requestId: pending.requestId, resultIndex: pending.resultIndex, primaryArtifactId: pending.primaryArtifactId } : null, lifecycle: lifecycle ? { sectionInstanceId: lifecycle.sectionInstanceId, targetGeneration: lifecycle.targetGeneration } : null, pickerValue: picker?.value ?? null, selectedResultIndex: table?.options?.selectedResultIndex ?? null, tableArtifactId: table?.resultArtifactId ?? null }; })()"
    When I evaluate "(async () => { const deadline = Date.now() + 10000; const raw = value => value && typeof value === 'object' ? value.full ?? value.display : value; while (Date.now() < deadline) { const section = document.getElementById('query_session_run_all'); const table = section?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); const columns = (table?.columns || []).map(column => typeof column === 'string' ? column : column.name); const row = table?.rows?.[0] || []; if (picker?.value === '1' && table?.options?.selectedResultIndex === 1 && raw(row[columns.indexOf('ResultSet')]) === 'second' && Number(raw(row[columns.indexOf('Value')])) === 2) return 'Result 2 accepted after sticky reopen'; await new Promise(resolve => setTimeout(resolve, 50)); } throw new Error('Could not switch sticky reopened results to Result 2'); })()" in the webview "session.kqlx" for 15 seconds
    Then I collect JSON artifact "reopened-sticky-switched-to-result-two" from webview expression "(() => { const raw = value => value && typeof value === 'object' ? value.full ?? value.display : value; const section = document.getElementById('query_session_run_all'); const table = section?.querySelector('kw-data-table'); const picker = table?.shadowRoot?.querySelector('[data-testid=result-set-picker]'); const columns = (table?.columns || []).map(column => typeof column === 'string' ? column : column.name); const row = table?.rows?.[0] || []; if (picker?.value !== '1' || table?.options?.selectedResultIndex !== 1 || raw(row[columns.indexOf('ResultSet')]) !== 'second' || Number(raw(row[columns.indexOf('Value')])) !== 2) throw new Error('Sticky reopened Result 2 state is incorrect'); return { selectedResultIndex: table.options.selectedResultIndex, row: row.map(raw) }; })()"
    When I execute command "workbench.action.focusActiveEditorGroup"
    And I move the mouse to 30, 700
    And I click
    And I press "Escape"
    And I wait 1 second
    Then I take a screenshot "01-reopened-result-two"

    When I execute command "kustoWorkbench.test.closeQueryEditorSession"