Feature: SQL results feed dependent sections

  Background:
    Given the extension is in a clean state
    When I execute command "kusto.openQueryEditor"
    And I wait 3 seconds
    When I evaluate "window.__e2e.workbench.clearSections()" in the webview
    When I wait for "button[data-add-kind='sql']" in the webview for 20 seconds
    When I click "button[data-add-kind='sql']" in the webview
    When I wait for "kw-sql-section[data-test-sql-connection='true']" in the webview for 60 seconds
    When I wait for "kw-sql-section[data-test-databases-loading='false'][data-test-has-databases='true']" in the webview for 30 seconds
    When I evaluate "window.__e2e.sql.selectDatabase('sampledb')" in the webview
    When I wait for "kw-sql-section[data-test-schema-ready='true']" in the webview for 60 seconds
    When I wait for "kw-sql-section[data-test-sts-ready='true']" in the webview for 120 seconds

  Scenario: Transformation, Chart, and HTML consume live STS results
    When I evaluate "window.__e2e.sql.setQuery('SELECT 1 AS Category, 10 AS Amount UNION ALL SELECT 2, 20 UNION ALL SELECT 3, 30')" in the webview
    When I evaluate "window.__e2e.sql.run()" in the webview
    When I wait for "kw-sql-section[data-test-executing='false'][data-test-has-results='true']" in the webview for 30 seconds
    When I evaluate "(() => { const sql = document.querySelector('kw-sql-section'); if (!sql || !sql.boxId) throw new Error('SQL section unavailable'); const sourceId = sql.boxId; const transformId = window.addTransformationBox({ id: 'transformation_sql_contract', name: 'SQL Derived', dataSourceId: sourceId, transformationType: 'derive', deriveColumns: [{ name: 'DoubleAmount', expression: 'Amount * 2' }], mode: 'preview', expanded: true, afterBoxId: sourceId }); const transform = document.getElementById(transformId); if (!transform || typeof transform.refresh !== 'function') throw new Error('Transformation unavailable'); transform.refresh(); const chartId = window.addChartBox({ id: 'chart_sql_contract', name: 'SQL Chart', dataSourceId: transformId, chartType: 'bar', xColumn: 'Category', yColumns: ['DoubleAmount'], mode: 'preview', expanded: true, afterBoxId: transformId }); const chart = document.getElementById(chartId); if (!chart || typeof chart.refresh !== 'function') throw new Error('Chart unavailable'); chart.refresh(); const provenance = '<script type=\'application/kw-provenance\'>' + JSON.stringify({ version: 1, model: { fact: { sectionId: sourceId, sectionName: 'SQL Source' } }, bindings: { total: { display: { type: 'scalar', agg: 'COUNT' } } } }) + '</script><span data-kw-bind=\'total\'>0</span>'; const htmlId = window.addHtmlBox({ id: 'html_sql_contract', name: 'SQL HTML', code: provenance, mode: 'preview', expanded: true, previewHeightPx: 160, afterBoxId: chartId }); return JSON.stringify({ sourceId, transformId, chartId, htmlId }); })()" in the webview
    And I wait 3 seconds
    When I evaluate "(() => { const result = window.__e2e.sql.resultContract(); const sql = document.querySelector('kw-sql-section'); const transform = window.getResultsState ? window.getResultsState('transformation_sql_contract') : null; const actualTransform = transform || (window.__e2e && window.__e2e.workbench && document.getElementById('transformation_sql_contract')); const rs = window.__kustoGetChartDatasetsInDomOrder().find(d => d.id === 'transformation_sql_contract'); if (!rs) throw new Error('Transformation result dataset unavailable'); const names = rs.columns.map(c => typeof c === 'string' ? c : c.name); const idx = names.indexOf('DoubleAmount'); if (idx < 0) throw new Error('Derived column missing: ' + names.join(',')); const values = rs.rows.map(r => Number(r[idx])); if (JSON.stringify(values) !== JSON.stringify([20,40,60])) throw new Error('Derived values=' + JSON.stringify(values)); const validation = window.__kustoGetChartValidationStatus('chart_sql_contract'); if (!validation || validation.valid !== true) throw new Error('Chart validation=' + JSON.stringify(validation)); const chartState = window.__kustoGetChartState('chart_sql_contract'); if (!chartState || !chartState.__wasRendering || !chartState.__echarts || !chartState.__echarts.instance) throw new Error('Chart did not render from SQL transformation'); const html = document.getElementById('html_sql_contract'); const iframe = html && html.shadowRoot && html.shadowRoot.getElementById('preview-iframe'); const srcdoc = String(iframe && iframe.srcdoc || ''); if (!srcdoc.includes('KustoWorkbench') || !srcdoc.includes('10') || !srcdoc.includes('30')) throw new Error('HTML bridge missing SQL values; srcdoc length=' + srcdoc.length); if (!result || result.rows.length !== 3) throw new Error('SQL source rows changed'); return 'SQL dependent sections consumed live values'; })()" in the webview
    When I execute command "workbench.action.closeAllEditors"
