Feature: Host-owned Markdown section lifecycle

  Background:
    Given the extension is in a clean state
    And I capture the output channel "Kusto Workbench"
    When I move the Dev Host to 0, 0
    When I resize the Dev Host to 1280x1000
    When I execute command "workbench.action.closeAuxiliaryBar"

  Scenario: Markdown commands survive stale view state, save, and view recreation
    Given a file "tests/vscode-extension-tester/runs/default/host-owned-markdown-lifecycle/host-owned-markdown.kqlx" exists with content:
      """
      {"kind":"kqlx","version":1,"futureRoot":{"keep":"root"},"state":{"futureState":{"keep":true},"sections":[{"id":"markdown_doc1","type":"markdown","title":"Before","text":"before","mode":"markdown","expanded":true,"futureMarkdown":{"keep":"section-extension"}},{"id":"future_doc1","type":"future-section","payload":{"nested":[1,2,3]}}]}}
      """

    When I open file "tests/vscode-extension-tester/runs/default/host-owned-markdown-lifecycle/host-owned-markdown.kqlx" in the editor
    When I wait for "#markdown_doc1" in the webview for 20 seconds
    When I evaluate "(async () => { const deadline = Date.now() + 10000; while (Date.now() < deadline) { const section = document.getElementById('markdown_doc1'); const editor = window.__kustoMarkdownEditors?.markdown_doc1; if (section && editor) { window.__doc1MarkdownSerializeCalls = 0; window.__e2eCaptureHostMessage = message => { if (message?.type === 'markdownDocumentCommand') window.__doc1MarkdownSourceGeneration = message.sourceGeneration; return true; }; section.serialize = () => { window.__doc1MarkdownSerializeCalls++; throw new Error('stale Markdown DOM serializer'); }; section.setText('after'); section.setName('Host owned'); section.setMarkdownMode('preview'); section.setExpanded(true); section.commitDocumentState(); const temporaryId = window.addMarkdownBox({ id: 'markdown_doc1_temporary', title: 'Temporary', text: 'remove me' }); if (temporaryId !== 'markdown_doc1_temporary') throw new Error('Temporary Markdown add failed: ' + temporaryId); window.removeMarkdownBox(temporaryId); return { id: section.id, temporaryId }; } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Markdown editor did not initialize'); })()" in the webview for 15 seconds
    When I execute command "workbench.action.files.save"
    And I wait 1 second
    When I evaluate "(() => { if (!Number.isSafeInteger(window.__doc1MarkdownSourceGeneration)) throw new Error('Active Markdown source generation was not captured'); window.vscode.postMessage({ type: 'markdownDocumentCommand', commandId: 'doc1-native-stale', sourceGeneration: window.__doc1MarkdownSourceGeneration, expectedDocumentRevision: 0, command: { type: 'patch', sectionId: 'markdown_doc1', expectedSectionRevision: 0, patch: { text: 'stale overwrite' } } }); return 'stale command sent'; })()" in the webview
    And I wait 1 second
    When I evaluate "(() => { window.schedulePersist('doc1-native-poison', true); if (window.__doc1MarkdownSerializeCalls !== 0) throw new Error('Native persistence consulted Markdown serialize(): ' + window.__doc1MarkdownSerializeCalls); return { serializeCalls: window.__doc1MarkdownSerializeCalls }; })()" in the webview
    And I wait 2 seconds
    Then I collect JSON artifact "doc1-host-buffer-after-immediate-save" from extension host expression "(async () => { const suffix = '/tests/vscode-extension-tester/runs/default/host-owned-markdown-lifecycle/host-owned-markdown.kqlx'; const deadline = Date.now() + 10000; while (Date.now() < deadline) { const document = vscode.workspace.textDocuments.find(candidate => candidate.uri.path.replace(/\\/g, '/').endsWith(suffix)); if (document) { const file = JSON.parse(document.getText()); const ids = file.state.sections.map(section => section.id); const markdown = file.state.sections.find(section => section.id === 'markdown_doc1'); if (markdown?.text === 'after' && markdown?.title === 'Host owned' && !ids.includes('markdown_doc1_temporary')) { if (document.getText().includes('stale overwrite')) throw new Error('Stale command mutated the host buffer'); if (document.isDirty) throw new Error('Immediate Save did not settle the Markdown command burst'); return { ids, title: markdown.title, text: markdown.text, mode: markdown.mode, dirty: document.isDirty }; } } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Host-owned Markdown commands did not reach the document buffer'); })()"
    When I execute command "workbench.action.closeAllEditors"
    When I open file "tests/vscode-extension-tester/runs/default/host-owned-markdown-lifecycle/host-owned-markdown.kqlx" in the editor
    When I wait for "#markdown_doc1" in the webview for 20 seconds
    When I evaluate "(async () => { const section = document.getElementById('markdown_doc1'); await section.updateComplete; const deadline = Date.now() + 10000; while (Date.now() < deadline) { if (section.getText() === 'after' && section.getName() === 'Host owned') { if (document.getElementById('markdown_doc1_temporary')) throw new Error('Removed Markdown section returned after view recreation'); return { text: section.getText(), title: section.getName() }; } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Host-owned Markdown state did not restore after view recreation'); })()" in the webview for 15 seconds
    Then I take a screenshot "01-host-owned-markdown-restored"
    Then I collect JSON artifact "doc1-lossless-file" from extension host expression "(async () => { const suffix = '/tests/vscode-extension-tester/runs/default/host-owned-markdown-lifecycle/host-owned-markdown.kqlx'; const document = vscode.workspace.textDocuments.find(candidate => candidate.uri.path.replace(/\\/g, '/').endsWith(suffix)); if (!document) throw new Error('Open DOC-1 fixture not found'); const bytes = await vscode.workspace.fs.readFile(document.uri); const file = JSON.parse(new TextDecoder().decode(bytes)); const ids = file.state.sections.map(section => section.id); if (ids.join('|') !== 'markdown_doc1|future_doc1') throw new Error('Section order changed: ' + ids.join(',')); const markdown = file.state.sections[0]; if (markdown.title !== 'Host owned' || markdown.text !== 'after' || markdown.mode !== 'preview' || markdown.expanded !== true) throw new Error('Markdown command state was not saved: ' + JSON.stringify(markdown)); if (markdown.futureMarkdown?.keep !== 'section-extension') throw new Error('Known-section extension was lost'); if (file.futureRoot?.keep !== 'root' || file.state.futureState?.keep !== true) throw new Error('Future root/state data was lost'); if (file.state.sections[1].payload?.nested?.join(',') !== '1,2,3') throw new Error('Opaque section payload was lost'); if (document.isDirty) throw new Error('Reopened DOC-1 fixture is dirty'); return { ids, markdown: { title: markdown.title, text: markdown.text, mode: markdown.mode, expanded: markdown.expanded, futureMarkdown: markdown.futureMarkdown }, futureRoot: file.futureRoot, futureState: file.state.futureState, opaquePayload: file.state.sections[1].payload, dirty: document.isDirty }; })()"

    When I execute command "workbench.action.closeAllEditors"
    When I delete file "tests/vscode-extension-tester/runs/default/host-owned-markdown-lifecycle/host-owned-markdown.kqlx"