Feature: Restored Kusto sections execute on the first Run click

  Background:
    Given the extension is in a clean state
    And I capture the output channel "Kusto Workbench"
    When I move the Dev Host to 0, 0
    When I resize the Dev Host to 1280x1000
    When I execute command "workbench.action.closeAuxiliaryBar"
    When I execute command "notifications.clearAll"
    When I execute command "kusto.openQueryEditor"
    And I wait 3 seconds

  Scenario: First Run click repairs restored target ownership and persists its result
    When I execute command "workbench.action.closeAllEditors"
    When I execute command "kustoWorkbench.test.cleanupPersistedResultFixture"
    When I delete file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-first-run/restored-first-run.kqlx"
    When I execute command "kustoWorkbench.test.preparePersistedResultFixture" with args '[{"engine":"kusto","templatePath":"tests/vscode-extension-tester/e2e/default/persisted-results-restore/fixtures/persisted-results.kqlx","outputPath":"tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-first-run/restored-first-run.kqlx","existingClusterIncludes":"1es.kusto.windows.net","database":"Liquid"}]'
    When I open file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-first-run/restored-first-run.kqlx" in the editor
    When I wait for "#query_persisted_results[data-test-connection='true'][data-test-database-selected='true']" in the webview "restored-first-run.kqlx" for 30 seconds
    When I evaluate "window.__e2e.workbench.waitForPersistedResult('query_persisted_results', 19000)" in the webview "restored-first-run.kqlx" for 20 seconds
    When I evaluate "(async () => { const section = document.getElementById('query_persisted_results'); const connectionId = String(section?.getConnectionId?.() || ''); const database = String(section?.getDatabase?.() || ''); const before = section?.getSchemaLifecycleIdentity?.(); if (!section || !connectionId || !database || !before) throw new Error('Restored Kusto target is not ready'); const lagging = section.setSchemaLifecycleTarget(connectionId); if (!lagging || lagging.targetGeneration <= before.targetGeneration) throw new Error('Could not create the restored target-lag condition'); await section.updateComplete; if (section.dataset.testHasResults !== 'false') throw new Error('Target lag did not retire the prior rendered result'); window.__restoredFirstRunLag = { connectionId, database, targetGeneration: lagging.targetGeneration }; window.__e2e.kusto.beginHostMessageCapture(); return window.__restoredFirstRunLag; })()" in the webview "restored-first-run.kqlx"
    When I click "#query_persisted_results_run_btn" in the webview "restored-first-run.kqlx"
    When I wait for "#query_persisted_results[data-test-executing='false'][data-test-has-results='true']" in the webview "restored-first-run.kqlx" for 60 seconds
    Then I collect JSON artifact "restored-first-run" from webview expression "(() => { const section = document.getElementById('query_persisted_results'); const lag = window.__restoredFirstRunLag; const messages = window.__e2e.hostMessageCapture.messages.filter(message => message && (message.type === 'kustoSectionTarget' || message.type === 'executeQuery')); const targets = messages.filter(message => message.type === 'kustoSectionTarget'); const executions = messages.filter(message => message.type === 'executeQuery'); if (!lag || targets.length !== 1 || executions.length !== 1 || messages[0] !== targets[0] || messages[1] !== executions[0]) throw new Error('Expected exactly one click-triggered target repair followed by one execution: ' + JSON.stringify({ lag, messages })); const target = targets[0]; const execution = executions[0]; if (target.targetGeneration <= lag.targetGeneration || target.connectionId !== lag.connectionId || target.database !== lag.database || target.connectionId !== execution.connectionId || target.database !== execution.database || target.sectionInstanceId !== execution.sectionInstanceId || target.targetGeneration !== execution.targetGeneration) throw new Error('Run was not preceded by its exact newer repaired target: ' + JSON.stringify({ lag, messages })); const table = section?.querySelector('kw-data-table'); const raw = value => value && typeof value === 'object' ? value.full ?? value.display : value; const row = table?.rows?.[0]?.map(raw); if (table?.rows?.length !== 12 || Number(row?.[0]) !== 1 || row?.[1] !== 'persist_row_01') throw new Error('First Run click did not publish the expected result: ' + JSON.stringify({ rows: table?.rows?.length, row })); if (section.dataset.testHasError === 'true') throw new Error('First Run click rendered an error'); delete window.__restoredFirstRunLag; return { lagGeneration: lag.targetGeneration, execution: { executionId: execution.executionId, sectionInstanceId: execution.sectionInstanceId, targetGeneration: execution.targetGeneration, connectionId: execution.connectionId, database: execution.database }, repairedTarget: { targetGeneration: target.targetGeneration, connectionId: target.connectionId, database: target.database }, rowCount: table.rows.length, firstRow: row }; })()"
    When I execute command "notifications.clearAll"
    Then I take a screenshot "01-restored-first-run-result"
    When I evaluate "window.__e2e.kusto.restoreHostMessageCapture()" in the webview "restored-first-run.kqlx"
    When I execute command "workbench.action.files.save"
    Then I collect JSON artifact "restored-first-run-durable" from extension host expression "(async () => { const suffix = '/tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-first-run/restored-first-run.kqlx'; const document = vscode.workspace.textDocuments.find(candidate => candidate.uri.path.replace(/\\/g, '/').endsWith(suffix)); if (!document || document.isDirty) throw new Error('Saved first-click fixture is unavailable or dirty'); const deadline = Date.now() + 10000; while (Date.now() < deadline) { const file = JSON.parse(new TextDecoder().decode(await vscode.workspace.fs.readFile(document.uri))); const query = file.state.sections.find(section => section.id === 'query_persisted_results'); const result = query?.resultJson ? JSON.parse(query.resultJson) : null; const firstRow = result?.rows?.[0]?.map(value => value && typeof value === 'object' ? value.full ?? value.display : value); if (query?.resultArtifact?.revision === 2 && result?.rows?.length === 12 && Number(firstRow?.[0]) === 1 && firstRow?.[1] === 'persist_row_01') return { revision: query.resultArtifact.revision, artifactId: query.resultArtifact.artifactId, rowCount: result.rows.length, firstRow }; await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Durable first-click result did not settle at artifact revision 2'); })()"
    When I execute command "workbench.action.closeAllEditors"
    When I open file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-first-run/restored-first-run.kqlx" in the editor
    When I evaluate "window.__e2e.workbench.waitForPersistedResult('query_persisted_results', 19000)" in the webview "restored-first-run.kqlx" for 20 seconds
    Then I collect JSON artifact "restored-first-run-reopen" from webview expression "(() => { const section = document.getElementById('query_persisted_results'); const table = section?.querySelector('kw-data-table'); const raw = value => value && typeof value === 'object' ? value.full ?? value.display : value; const row = table?.rows?.[0]?.map(raw); if (table?.rows?.length !== 12 || Number(row?.[0]) !== 1 || row?.[1] !== 'persist_row_01' || table.resultArtifactId !== 'result:query_persisted_results:2') throw new Error('Saved first-click result did not survive reopen at revision 2: ' + JSON.stringify({ rows: table?.rows?.length, row, artifactId: table?.resultArtifactId })); return { rowCount: table.rows.length, firstRow: row, artifactId: table.resultArtifactId }; })()"
    When I execute command "workbench.action.closeAllEditors"
    When I execute command "kustoWorkbench.test.cleanupPersistedResultFixture"
    When I delete file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-first-run/restored-first-run.kqlx"