Feature: Capture multi-account screenshot
  Scenario: Cached Values viewer with multiple accounts
    When I move the Dev Host to 0, 0
    And I resize the Dev Host to 1100 by 600
    And I execute command "workbench.action.closeSidebar"
    And I execute command "workbench.action.closeAuxiliaryBar"
    And I execute command "workbench.action.toggleActivityBarVisibility"
    And I execute command "kusto.seeCachedValues"
    And I wait 5 seconds
    When I evaluate "eval(atob('Y29uc3Qgd2FsayA9IChuKSA9PiB7IGlmIChuLm5vZGVUeXBlID09PSAzKSB7IG4udGV4dENvbnRlbnQgPSBuLnRleHRDb250ZW50LnJlcGxhY2UoL2FuZ2VscGVAbWljcm9zb2Z0XC5jb20vZywgJ3VzZXJAZG9tYWluLmNvbScpLnJlcGxhY2UoL1swLTlhLWZdezh9LVswLTlhLWZdezR9LVswLTlhLWZdezR9LVswLTlhLWZdezR9LVswLTlhLWZdWzAtOWEtZi5dKy9nLCAnMTExMTExMTEtMjIyMi0zMzMzLTQ0NDQtNTU1NTU1NTU1NTU1JykucmVwbGFjZSgvZGRhenVyZWNsaWVudHMvZywgJ2NsdXN0ZXIxJykucmVwbGFjZSgvXGIxZXNcYi9nLCAnY2x1c3RlcjInKS5yZXBsYWNlKC9hb2FpYWdlbnRzMVwud2VzdHVzL2csICdjbHVzdGVyMycpLnJlcGxhY2UoL2RkdGVsdnNjb2RlL2csICdjbHVzdGVyNCcpOyB9IGVsc2UgeyBpZiAobi5zaGFkb3dSb290KSB7IGZvciAoY29uc3QgYyBvZiBuLnNoYWRvd1Jvb3QuY2hpbGROb2Rlcykgd2FsayhjKTsgfSBmb3IgKGNvbnN0IGMgb2Ygbi5jaGlsZE5vZGVzKSB3YWxrKGMpOyB9IH07IHdhbGsoZG9jdW1lbnQuYm9keSk7IGNvbnN0IHNyID0gZG9jdW1lbnQucXVlcnlTZWxlY3Rvcigna3ctY2FjaGVkLXZhbHVlcycpPy5zaGFkb3dSb290OyBpZiAoc3IpIHsgc3IucXVlcnlTZWxlY3RvckFsbCgnc2VsZWN0IG9wdGlvbicpLmZvckVhY2goKG8pID0+IHsgby50ZXh0Q29udGVudCA9IG8udGV4dENvbnRlbnQucmVwbGFjZSgvYW5nZWxwZUBtaWNyb3NvZnRcLmNvbS9nLCAndXNlckBkb21haW4uY29tJyk7IH0pOyBjb25zdCBzZWxlY3RzID0gc3IucXVlcnlTZWxlY3RvckFsbCgnc2VsZWN0Jyk7IGlmIChzZWxlY3RzWzFdKSB7IHNlbGVjdHNbMV0ucXVlcnlTZWxlY3RvckFsbCgnb3B0aW9uJykuZm9yRWFjaChvID0+IHsgby50ZXh0Q29udGVudCA9IG8udGV4dENvbnRlbnQucmVwbGFjZSgvdXNlckBkb21haW5cLmNvbS9nLCAndXNlcjJAZG9tYWluMi5jb20nKTsgfSk7IH0gfSAnZmFrZWQn'))" in the webview "Cached Values"
    And I wait 2 seconds
    Then I take a screenshot "01-multi-account"
