Feature: Restored Kusto readiness with Power BI dashboard

  Background:
    Given the extension is in a clean state
    And I capture the output channel "Kusto Workbench"
    When I execute command "workbench.action.closeAuxiliaryBar"
    When I execute command "workbench.action.closeAllEditors"
    And I wait 2 seconds
    When I delete file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-dashboard-readiness/old-query-dashboard.kqlx"
    And I wait 1 second

  Scenario: Background refresh stays quiet after restored IntelliSense is ready
    Given a file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-dashboard-readiness/old-query-dashboard.kqlx" exists with content:
      """
      {"kind":"kqlx","version":1,"state":{"sections":[{"id":"old_query","type":"query","name":"Old Query","query":"print RestoredSection = 1","expanded":true,"clusterUrl":"https://1es.kusto.windows.net","database":"Liquid"},{"id":"old_powerbi_dashboard","type":"html","name":"Old Power BI Dashboard","code":"<script type=\"application/kw-provenance\">{\"version\":1,\"model\":{\"fact\":{\"sectionId\":\"old_query\",\"sectionName\":\"Old Query\"}},\"bindings\":{\"total\":{\"display\":{\"type\":\"scalar\",\"agg\":\"COUNT\"}}}}</script><span data-kw-bind=\"total\">0</span>","mode":"preview","expanded":true,"previewHeightPx":160}]}}
      """
    And I wait 1 second
    When I open file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-dashboard-readiness/old-query-dashboard.kqlx" in the editor
    When I wait for "#old_query" in the webview for 20 seconds
    When I wait for "#old_powerbi_dashboard" in the webview for 20 seconds
    When I click "#old_query .query-editor" in the webview
    When I evaluate "window.__e2e.kusto.waitForWorkerContext(0, 20000)" in the webview for 25 seconds
    When I evaluate "window.__e2e.kusto.assertActualWorkerContext(0)" in the webview for 10 seconds
    When I evaluate "(() => { const enabled = window.__e2e.kusto.setCustomColumnProviderEnabled(false, 0); if (enabled !== false) throw new Error('Old query auxiliary provider was not disabled'); return 'old query auxiliary provider disabled'; })()" in the webview
    When I evaluate "window.__e2e.kusto.assertTableCompletionForSection(0, 20000, 'restored-dashboard-table-completion')" in the webview for 25 seconds
    When I wait for "[data-testid='e2e-proof-restored-dashboard-table-completion']" in the webview for 5 seconds
    When I evaluate "(() => { const enabled = window.__e2e.kusto.setCustomColumnProviderEnabled(true, 0); if (enabled !== true) throw new Error('Old query auxiliary provider was not enabled'); return 'old query auxiliary provider enabled'; })()" in the webview
    When I evaluate "(async () => { const section = document.getElementById('old_query'); const dashboard = document.getElementById('old_powerbi_dashboard'); if (!section || !dashboard) throw new Error('Restored query/dashboard composition is incomplete'); const deadline = performance.now() + 20000; let refreshRequestedForTarget = 0; let last = null; while (performance.now() < deadline) { const during = window.__e2e.kusto.schemaLifecycleSnapshot().sections.find(entry => entry.boxId === 'old_query'); last = during; const exactWorker = during?.worker?.status === 'ready' && during.worker.modelMatches && during.worker.preparationMatches; const blockers = during?.preparation?.blockers || []; const backgroundRefresh = during?.preparation?.status === 'preparing' && during.preparation.stage === 'refreshing' && during.preparation.usableFallback === true && blockers.includes('refresh') && blockers.every(blocker => blocker === 'refresh' || blocker === 'worker' || blocker === 'enhancement'); if (exactWorker && backgroundRefresh) { const toolbar = section.querySelector('.query-editor-toolbar'); const progress = toolbar ? getComputedStyle(toolbar, '::after') : null; const animation = String(progress?.animationName || ''); const content = String(progress?.content || ''); if (section.getAttribute('aria-busy') !== 'false' || content !== 'none' || animation.includes('kusto-section-preparing')) throw new Error('Activity line remained after IntelliSense was ready: ' + JSON.stringify({ content, animation, during })); const dashboardPreview = dashboard.shadowRoot?.getElementById('preview-iframe'); const dashboardSource = dashboardPreview?.srcdoc || dashboardPreview?.getAttribute('srcdoc') || ''; if (!dashboardSource.includes('data-kw-bind') || !dashboardSource.includes('total')) throw new Error('Power BI dashboard preview did not restore'); window.__e2eBackgroundRefreshProof = { targetGeneration: during.targetGeneration, generation: during.preparation.generation, blockers: [...blockers], during, ariaBusy: section.getAttribute('aria-busy'), content, animation, dashboardPresent: true }; return window.__e2eBackgroundRefreshProof; } if (exactWorker && during?.catalog?.hasRawSchema && refreshRequestedForTarget !== during.targetGeneration) { refreshRequestedForTarget = during.targetGeneration; section.connectionCtrl.ensureSchema(true); } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Stable exact-worker background refresh did not arrive: ' + JSON.stringify(last)); })()" in the webview for 25 seconds
    Then I collect JSON artifact "restored-dashboard-background-refresh" from webview expression "window.__e2eBackgroundRefreshProof"
    When I move the Dev Host to 0, 0
    And I resize the Dev Host to 1300 by 950
    Then I take a screenshot "01-restored-dashboard-no-activity-line"
    When I evaluate "(() => { const section = document.getElementById('old_query'); const current = window.__e2e.kusto.schemaLifecycleSnapshot().sections.find(entry => entry.boxId === 'old_query'); const proof = window.__e2eBackgroundRefreshProof; if (!section || !current || !proof) throw new Error('Post-screenshot readiness state missing'); const stillRefreshing = current.preparation.status === 'preparing' && current.preparation.stage === 'refreshing' && JSON.stringify(current.preparation.blockers) === JSON.stringify(proof.blockers); const refreshCompleted = current.preparation.status === 'ready' && current.preparation.stage === 'ready' && current.preparation.blockers.length === 0; if (current.targetGeneration !== proof.targetGeneration || current.preparation.generation !== proof.generation || (!stillRefreshing && !refreshCompleted) || current.worker?.status !== 'ready' || !current.worker.modelMatches || !current.worker.preparationMatches) throw new Error('Background refresh generation or exact worker changed after screenshot: ' + JSON.stringify({ proof, current })); const toolbar = section.querySelector('.query-editor-toolbar'); const progress = toolbar ? getComputedStyle(toolbar, '::after') : null; const animation = String(progress?.animationName || ''); const content = String(progress?.content || ''); if (section.getAttribute('aria-busy') !== 'false' || content !== 'none' || animation.includes('kusto-section-preparing')) throw new Error('Activity line resumed after screenshot: ' + JSON.stringify({ content, animation })); return { targetGeneration: current.targetGeneration, generation: current.preparation.generation, status: current.preparation.status, stage: current.preparation.stage, blockers: current.preparation.blockers, ariaBusy: section.getAttribute('aria-busy'), content, animation }; })()" in the webview
    When I evaluate "(() => { window.schedulePersist('e2e-cleanup', true); return 'cleanup persistence scheduled'; })()" in the webview
    And I wait 3 seconds
    When I execute command "workbench.action.files.save"
    And I wait 3 seconds
    When I execute command "workbench.action.closeAllEditors"
    When I delete file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-dashboard-readiness/old-query-dashboard.kqlx"
