Feature: Restored multi-section Kusto startup without editor focus

  Background:
    Given the extension is in a clean state
    And I capture the output channel "Kusto Workbench"
    When I execute command "workbench.action.closeAuxiliaryBar"

  Scenario: All restored sections stop showing preparation before any editor click
    Given a file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-startup/five-section-startup.kqlx" exists with content:
      """
      {"kind":"kqlx","version":1,"state":{"caretDocsEnabled":true,"autoTriggerAutocompleteEnabled":true,"sections":[{"id":"startup_no_focus_1","type":"query","query":"Accountability_LeaderToDeputyCISO_Snapshot | take 1","expanded":true,"clusterUrl":"https://1es.kusto.windows.net","database":"Liquid"},{"id":"startup_no_focus_2","type":"query","query":"AzdOperations | take 1","expanded":true,"clusterUrl":"https://1es.kusto.windows.net","database":"DevCLI"},{"id":"startup_no_focus_3","type":"query","query":"AzdKPIs | take 1","expanded":true,"clusterUrl":"https://1es.kusto.windows.net","database":"DevCLI"},{"id":"startup_no_focus_4","type":"query","query":"Templates | take 1","expanded":true,"clusterUrl":"https://1es.kusto.windows.net","database":"DevCLI"},{"id":"startup_no_focus_5","type":"query","query":"AzdProvisionsByAzService | take 1","expanded":true,"clusterUrl":"https://1es.kusto.windows.net","database":"DevCLI"}]}}
      """
    When I open file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-startup/five-section-startup.kqlx" in the editor
    When I evaluate "(async () => { const deadline = performance.now() + 30000; while (performance.now() < deadline) { const sections = [...document.querySelectorAll('kw-query-section')]; const snapshot = window.__e2e?.kusto?.schemaLifecycleSnapshot?.(); const entries = snapshot?.sections || []; const complete = !window.activeQueryEditorBoxId && sections.length === 5 && entries.length === 5 && entries.every(entry => entry.modelAttached && entry.catalog?.hasRawSchema && entry.pending && entry.preparation?.status === 'deferred' && entry.preparation?.stage === 'waiting-focus' && entry.preparation?.blockers?.length === 0); if (complete) return entries.map(entry => ({ boxId: entry.boxId, targetGeneration: entry.targetGeneration, preparation: entry.preparation, pending: entry.pending, catalog: entry.catalog })); await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Restored startup did not defer cleanly: ' + JSON.stringify({ activeQueryEditorBoxId: window.activeQueryEditorBoxId || null, lifecycle: window.__e2e?.kusto?.schemaLifecycleSnapshot?.() || null })); })()" in the webview for 35 seconds
    When I evaluate "(() => { const sections = [...document.querySelectorAll('kw-query-section')]; if (sections.length !== 5) throw new Error('Expected 5 sections, got ' + sections.length); return sections.map(section => { const toolbar = section.querySelector('.query-editor-toolbar'); const progress = toolbar ? getComputedStyle(toolbar, '::after') : null; const animation = String(progress?.animationName || ''); if (section.getAttribute('aria-busy') !== 'false') throw new Error(section.id + ' remained aria-busy'); if (section.dataset.testPreparationState !== 'deferred' || section.dataset.testPreparationStage !== 'waiting-focus' || section.dataset.testPreparationBlockers) throw new Error(section.id + ' has unexpected preparation: ' + JSON.stringify({ state: section.dataset.testPreparationState, stage: section.dataset.testPreparationStage, blockers: section.dataset.testPreparationBlockers })); if (animation.includes('kusto-section-preparing')) throw new Error(section.id + ' still shows the preparation animation'); return { id: section.id, ariaBusy: section.getAttribute('aria-busy'), state: section.dataset.testPreparationState, stage: section.dataset.testPreparationStage, animation }; }); })()" in the webview
    Then I collect JSON artifact "restored-no-focus-state" from webview expression "(() => window.__e2e.kusto.schemaLifecycleSnapshot())()"

    When I click "#startup_no_focus_1 .query-editor" in the webview
    When I evaluate "window.__e2e.kusto.waitForPreparationReady(0, 30000)" in the webview for 35 seconds
    When I evaluate "(async () => { const deadline = performance.now() + 3000; while (performance.now() < deadline) { const sections = [...document.querySelectorAll('kw-query-section')]; const snapshot = window.__e2e.kusto.schemaLifecycleSnapshot(); const first = snapshot.sections.find(entry => entry.boxId === 'startup_no_focus_1'); const rest = snapshot.sections.filter(entry => entry.boxId !== 'startup_no_focus_1'); if (first?.preparation?.status !== 'ready' || first?.worker?.status !== 'ready' || !first.worker.modelMatches) throw new Error('Focused worker lost readiness: ' + JSON.stringify(first)); if (rest.some(entry => entry.preparation?.status !== 'deferred' || entry.preparation?.blockers?.length !== 0)) throw new Error('An unfocused section changed state: ' + JSON.stringify(rest)); if (sections[0]?.getAttribute('aria-busy') !== 'false') throw new Error('Focused section remained busy'); await new Promise(resolve => setTimeout(resolve, 100)); } return 'focused worker remained ready while four sections stayed deferred'; })()" in the webview for 5 seconds
    Then I collect JSON artifact "focused-worker-state" from webview expression "(() => window.__e2e.kusto.schemaLifecycleSnapshot())()"

    When I execute command "workbench.action.files.save"
    When I execute command "workbench.action.closeAllEditors"
    When I open file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-startup/five-section-startup.kqlx" in the editor
    When I evaluate "(async () => { const deadline = performance.now() + 15000; while (performance.now() < deadline) { const sections = [...document.querySelectorAll('kw-query-section')]; const snapshot = window.__e2e?.kusto?.schemaLifecycleSnapshot?.(); const entries = snapshot?.sections || []; if (!window.activeQueryEditorBoxId && sections.length === 5 && entries.length === 5 && entries.every(entry => entry.modelAttached && entry.catalog?.hasRawSchema && entry.preparation?.status === 'deferred' && entry.preparation?.stage === 'waiting-focus' && entry.preparation?.blockers?.length === 0)) return entries.map(entry => ({ boxId: entry.boxId, preparation: entry.preparation, pending: entry.pending || null })); await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Reopened startup did not settle without focus: ' + JSON.stringify({ activeQueryEditorBoxId: window.activeQueryEditorBoxId || null, lifecycle: window.__e2e?.kusto?.schemaLifecycleSnapshot?.() || null })); })()" in the webview for 20 seconds
    When I evaluate "(() => { const sections = [...document.querySelectorAll('kw-query-section')]; for (const section of sections) { const toolbar = section.querySelector('.query-editor-toolbar'); const animation = String(toolbar ? getComputedStyle(toolbar, '::after')?.animationName || '' : ''); if (section.getAttribute('aria-busy') !== 'false' || animation.includes('kusto-section-preparing')) throw new Error(section.id + ' resumed infinite progress after reopen'); } return sections.map(section => section.id); })()" in the webview
    Then I collect JSON artifact "reopened-no-focus-state" from webview expression "(() => window.__e2e.kusto.schemaLifecycleSnapshot())()"
    When I execute command "workbench.action.closeAllEditors"
    When I delete file "tests/vscode-extension-tester/runs/kusto-auth/kusto-restored-startup/five-section-startup.kqlx"
