Feature: Add ordinary Kusto connection through the real form

  Background:
    Given the extension is in a clean state
    When I execute command "kusto.manageConnections"
    And I wait 2 seconds
    When I execute command "kustoWorkbench.test.cleanupKustoIdentityChecklist"
    When I execute command "kusto.manageConnections"
    When I move the Dev Host to 0, 0
    When I resize the Dev Host to 1280x1000
    When I execute command "workbench.action.closeAuxiliaryBar"

  Scenario: Authority-less connection is saved and remains editable
    When I wait for "[data-testid='cm-add-connection']" in the webview "Connection Manager" for 20 seconds
    When I evaluate "(async () => { const root = document.querySelector('kw-connection-manager')?.shadowRoot; root?.querySelector('[data-testid=cm-add-connection]')?.click(); await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))); const form = root?.querySelector('[data-testid=cm-modal-content] kw-kusto-connection-form'); if (!form) throw new Error('Add Connection form did not open'); const formRoot = form.shadowRoot; const setInput = (id, value) => { const input = formRoot.querySelector('[data-testid=' + id + ']'); if (!input) throw new Error('Missing ' + id); input.value = value; input.dispatchEvent(new Event('input', { bubbles: true, composed: true })); }; setInput('kusto-conn-name', 'E2E Identity Checklist Normal UI'); setInput('kusto-conn-cluster-url', 'identity-prod.kusto.windows.net'); setInput('kusto-conn-database', 'Samples'); const authority = formRoot.querySelector('[data-testid=kusto-conn-authority-id]'); const account = formRoot.querySelector('[data-testid=kusto-conn-account]'); if (authority?.value) throw new Error('Ordinary connection unexpectedly has an authority'); if (account?.value) throw new Error('Ordinary connection unexpectedly selected an explicit account'); root.querySelector('[data-testid=cm-modal-content] .modal-footer .btn.primary')?.click(); const deadline = Date.now() + 10000; while (Date.now() < deadline) { const row = Array.from(root.querySelectorAll('[data-testid=cm-kusto-connection-row]')).find(candidate => candidate.querySelector('.explorer-list-item-name')?.textContent?.trim() === 'E2E Identity Checklist Normal UI'); if (row && !root.querySelector('[data-testid=cm-modal-overlay]')) { const tenant = Array.from(row.querySelectorAll('.explorer-list-item-meta')).find(node => node.textContent?.trim().startsWith('Tenant:')); if (tenant) throw new Error('Ordinary row rendered a tenant: ' + tenant.textContent); return { saved: true, name: 'E2E Identity Checklist Normal UI', url: row.querySelector('.explorer-list-item-url')?.textContent?.trim(), authority: null, account: 'Automatic' }; } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Ordinary connection was not persisted through Add/Save'); })()" in the webview "Connection Manager" for 15 seconds
    Then I collect JSON artifact "ordinary-connection-ui" from webview expression "(async () => { const root = document.querySelector('kw-connection-manager')?.shadowRoot; const row = Array.from(root?.querySelectorAll('[data-testid=cm-kusto-connection-row]') || []).find(candidate => candidate.querySelector('.explorer-list-item-name')?.textContent?.trim() === 'E2E Identity Checklist Normal UI'); if (!row) throw new Error('Saved ordinary connection row missing'); row.querySelector('button[title=Edit]')?.click(); await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))); const form = root.querySelector('[data-testid=cm-modal-content] kw-kusto-connection-form'); await form?.updateComplete; const authority = form?.shadowRoot?.querySelector('[data-testid=kusto-conn-authority-id]'); const account = form?.shadowRoot?.querySelector('[data-testid=kusto-conn-account]'); if (!authority || !account) throw new Error('Edit form controls were not rendered'); if (authority.value) throw new Error('Edit form restored an unexpected authority'); if (account.value || account.selectedOptions?.[0]?.textContent?.trim() !== 'Automatic') throw new Error('Edit form did not restore Automatic account: value=' + account.value + ' text=' + account.selectedOptions?.[0]?.textContent?.trim()); return { saved: true, authority: null, account: 'Automatic' }; })()" in the webview "Connection Manager"
    When I execute command "workbench.action.focusActiveEditorGroup"
    Then I take a screenshot "01-ordinary-connection-saved"
    When I execute command "kustoWorkbench.test.cleanupKustoIdentityChecklist"